<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.29">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Results – Jon Minton — Academic Works</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bcbce66894bfa8e7e94e40e0186b9bb8.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-4e7a6ecc11b04d2331dcee725084a9de.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bcbce66894bfa8e7e94e40e0186b9bb8.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-e82830839f0dbc10de52f10233cbe019.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-560053cd89a245a3e0012c1d2476588d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-e82830839f0dbc10de52f10233cbe019.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Jon Minton — Academic Works</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../beng/index.html" aria-current="page"> 
<span class="menu-text">BEng</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../ma/index.html"> 
<span class="menu-text">MA</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../phd/index.html"> 
<span class="menu-text">PhD</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/JonMinton/academic-works"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://jonminton.net"> 
<span class="menu-text">jonminton.net</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../beng/abstract.html">Thesis</a></li><li class="breadcrumb-item"><a href="../beng/results.html">Results</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../beng/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">BEng: An Investigation Into Machine Vision Calibration Systems</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Thesis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../beng/abstract.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Abstract</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../beng/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../beng/theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Theory</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../beng/methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methods and Process</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../beng/results.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Results</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../beng/conclusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Discussion and Conclusion</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../beng/appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Code</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../beng/code-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Code Overview: MATLAB to Python Port</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../beng/abstract.html">Thesis</a></li><li class="breadcrumb-item"><a href="../beng/results.html">Results</a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Results</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>4</p>
<p><strong>&nbsp;Results</strong></p>
<p><strong><em>4.1 Section Introduction</em></strong></p>
<p>This section provides results attained through the use and creation of the prototype system. It is split into three sub-sections:&nbsp;</p>
<p>Results of all processes to a single test example.</p>
<p>Results of various processes to other example inputs.</p>
<p>Results required for machine calibration and testing system stability.</p>
<p><strong><em>Results Of System Using Single Test Case</em></strong></p>
<p><strong><em>Introduction</em></strong></p>
<p>Here, the stages of the prototype system listed in section 3 are demonstrated using a single test case.</p>
<p>In the test case, the bounded area was a rectangle 70mm wide and 50 mm high. This was marked out using four black square blocks 10 mm wide. Black was used as the marker colour as it is a poor choice of marker colour (due to the reasons given in section 2.3.2), and so demonstrating that the system works with this colour scheme suggest that it should also work with others (where the affect of bright lights and shadows can be more easily mitigated).</p>
<p>The object is represented by a small movable red rectangle 8mm wide and 6 mm high. Am image of this object within the bounded area, at the ‘correct’ position, is taken, and loaded, as an archived image, into the system at the start of the program sequence:</p>
<p><em>Archive image of marker object (red rectangle) in correct position</em></p>
<p><em>[Fig. 4.2.1]</em></p>
<p>Note that, within the bounded area, other objects, of a different colour, also exist. To work, the prototype system should not be affected by the position of these other objects. The background is graph paper, which, as a repeating pattern, creates ‘noise’ when a DIC approach is used (due to localised areas of image correlation). Both of these factors make the test case good for demonstrating the rigorousness of the system.</p>
<p>The geometry of the markers is also entered into the system at the start. The position of the four markers, from each other and in millimetres, is loaded into the system as the following 4 x 2 element array:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>0</th>
<th>0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>70</td>
<td>0</td>
</tr>
<tr class="even">
<td>0</td>
<td>50</td>
</tr>
<tr class="odd">
<td>70</td>
<td>50</td>
</tr>
</tbody>
</table>
<p><em>Marker position matrix used</em></p>
<p><em>[Table. 4.2.1]</em></p>
<p>Where the first column gives the horizontal distance from the origin, and the second gives the vertical distance from the origin.</p>
<p>Also given are information on the colour combination to use to find both the object marker (red), and the boundary markers (black). In the case of the boundary marker, this would be an instruction to convert the colour image into a greyscale image (by combining the pixel average of the three colour intensity plane) and then inverting, so dark areas become areas of high intensity. In the case of the red object marker, the procedure shown in section 2.3.3 is used.&nbsp;</p>
<p>The physical apparatus used for the test is as follows: A webcam is fixed to a certain position on ruler. The head of the webcam is fixed, vertically aligned with reference to its base, and facing forwards in the direction parallel to that of the ruler. At the end of the ruler a small cocktail is attached, propagating from the centre of the ruler width a small distance beyond that of the ruler. This provides a thin fulcrum about which the camera may rotate in the horizontal plane normal to the object plane, which is one of the walls of the room.&nbsp;</p>
<p><em>Image of the camera apparatus used</em></p>
<p><em>[Fig. 4.2.2]</em>**</p>
<p>The ruler is rested on the top of a table that is horizontally balanced with the markers on the object plane, and at a height such that the camera image is at the same height as the bounded area of the object plane. This reduces the number of positional factors that need to be considered, and that the effect of a single variable can be more easily isolated.&nbsp;</p>
<p><strong><em>Stage 1a: Finding Rotation Parallel To Plane</em></strong></p>
<p><strong><em>Determining Centres Of Markers</em></strong></p>
<p>If, to begin with, the camera image is at both the wrong angle in the plane parallel to the image, and horizontally perpendicular to it, then its position can be corrected one stage at time. To begin with, the angle of rotation parallel to the image plane is compensated found.</p>
<p>In the test example, the first image entered into the prototype system was as shown below on the left. The prototype first identified the boundary markers as shown below on the right:</p>
<p><em>The first camera image (left) and the marker mask of the image (right)</em></p>
<p><em>[Fig. 4.2.3]</em></p>
<p>Four sub-masks are then formed from this mask, effectively splitting the mask up into four quarters. The sub-masks are adjusted such that the corner of the quarter is at the origin of the sub-mask (e.g.&nbsp;for the bottom right quarter, the sub-image is flipped horizontally and vertically; for the top right quarter, the image is just flipped horizontally).</p>
<p>The co-ordinates of the centres of mass (and thus the central points of each marker) of each quarter are then located using the method described in section 2.3.4, giving the co-ordinates of the centre of the image from the corner of the image it is closest to:</p>
<p><em>(a) (b) (c) (d)</em></p>
<p><em>Sub-masks of the (a) top left, (b) top right, (c) bottom left, and (d) bottom right quarters of the mask image</em></p>
<p><em>[Fig. 4.2.4]</em></p>
<pre><code>  ****
  **************
  **************


  **
  **
  ******
  **
  **
  ******


  **
  
  
  
  
  
  


  **
  
  
  
  
  
  


  **
  
  
  
  
  
  


  **
  
  
  
  
  
  </code></pre>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Quarter</th>
<th>Horizontal distance… (in pixels)</th>
<th>Vertical distance… (in pixels)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>To start of marker block</td>
<td>To centre of marker block</td>
<td>From corner</td>
</tr>
<tr class="even">
<td>Top Left</td>
<td>74</td>
<td>20.6</td>
</tr>
<tr class="odd">
<td>Top Right</td>
<td>28</td>
<td>16.2</td>
</tr>
<tr class="even">
<td>Bottom Left</td>
<td>60</td>
<td>20.9</td>
</tr>
<tr class="odd">
<td>Bottom Right</td>
<td>37</td>
<td>17.6</td>
</tr>
</tbody>
</table>
<p><em>Table of centre point positions calculated</em></p>
<p><em>[Table. 4.2.2]</em>**</p>
<p>&nbsp;</p>
<p>These results are used to determine the following co-ordinate positions for the centre of the markers in the image as a whole:</p>
<pre><code>  ****
  ****


  
  


  
  


  
  


  
  </code></pre>
<table class="caption-top table">
<thead>
<tr class="header">
<th>x</th>
<th>y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>94.6</td>
<td>48.8</td>
</tr>
<tr class="even">
<td>275.8</td>
<td>71.8</td>
</tr>
<tr class="odd">
<td>80.9</td>
<td>177.7</td>
</tr>
<tr class="even">
<td>265.4</td>
<td>189.6</td>
</tr>
</tbody>
</table>
<p><em>Coordinates of the centres of the markers, in pixels</em></p>
<p><em>[Table. 4.2.3]</em>**</p>
<p>These positions are represented on the image below as the red points on the greyscale version of the input image, and the mask used to calculate them:</p>
<p><em>(a) (b)</em></p>
<p><em>&nbsp; Coordinates of the centres of the markers, superimposed (a) on mask, and (b) on greyscale version of input image</em></p>
<p><em>[Fig. 4.2.5]</em>**</p>
<p>&nbsp; &nbsp;</p>
<p><strong><em>Determining Rotation</em></strong></p>
<p>It is now relatively simple to determine the plane-parallel rotation of the camera to the object plane. The process is as follows:</p>
<p>Compare the vertical distance between the two points on the left (Left half of image), with the two points on the right (Right half of image). The camera is closer to the side whose points are further apart. In the test case, the two points on the left are further apart.</p>
<p>The points from this half are more accurate representations of the centres of the markers, as the camera is closer to them, and thus their effective resolution in the image is higher. Due to the way the markers are formed, borderlines of a certain number of pixels are created which extend slightly beyond the boundaries of the marker in the original image (Fig. 2.3.10; Fig 2.3.11). The distortion of the marker shape and position due to these borderlines are greater if the marker is smaller; thus the larger (in this case closer) markers provide more accurate estimates of their central positions. These two position co-ordinates on the left side are considered thus those used to determine the angle.</p>
<p>The horizontal displacement between the two points is divided by the vertical displacement, and the tangent of this value if found to determine the angle between the two markers.</p>
<p>If the angle is small (less than one degree in magnitude, in the case of the prototype), then the program passes to the next stage. Otherwise, the angle between the two points is given to the user, together with instructions on what action to take. In the test case, the first input image yields and angle of –6.1 degrees (due to the way positive and negative displacement is defined, and the instruction:&nbsp;</p>
<p>Rotate Camera in parallel with plane:</p>
<p>6.1</p>
<p>degrees anticlockwise</p>
<pre><code>is given to the user.</code></pre>
<p>The prototype now waits for the user to reposition the camera, and take a second image. When the user indicates, the prototype loads in the new image, and performs the same analysis on this as it did on the first. In the test case, the new image was:</p>
<p><em>Second (position adjusted) image</em></p>
<p><em>[Fig. 4.2.6]</em>**</p>
<p>This time, the plane-parallel angle was within the one degree acceptable limit (Calculated as –0.3 degrees), yielding the following output:</p>
<p>Rotational Angle OK</p>
<p>The program now passes the image to the next stage.</p>
<p><strong><em>Stage 1b: Finding Horizontal Rotation Normal To Plane</em></strong></p>
<p>The next stage is to correct the angle of the camera in the horizontal plane normal to the object plane. The process is as follows:</p>
<p>A mask of the image is created:</p>
<p><em>Mask of second image</em></p>
<p><em>[Fig. 4.2.7]</em>**</p>
<p>and the centres of each of the markers are found using the method detailed in section 4.2.2.1.&nbsp;</p>
<p>The vertical distances between the top left and the bottom left, and the top right and bottom right, marker points are found, and the ratio between them is found. In the test case, the positions of the centres of the four points, with respect to the top left point, are:</p>
<pre><code>  ****
  ****
  ****


  ******
  
  


  ******
  
  


  ******
  
  


  ******
  
  </code></pre>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Point</th>
<th>x</th>
<th>y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Top Left</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Top Right</td>
<td>179.8</td>
<td>9.7</td>
</tr>
<tr class="odd">
<td>Bottom Left</td>
<td>-0.7</td>
<td>131.0</td>
</tr>
<tr class="even">
<td>Bottom Right</td>
<td>182.0</td>
<td>126.2</td>
</tr>
</tbody>
</table>
<p><em>Relative positions of marker centres</em></p>
<p><em>[Table. 4.2.4]</em>**</p>
<p>The left side vertical value is thus: 131.0 – 0 = <strong>131.0</strong></p>
<p>&nbsp; And the right side vertical value is: 126.2 – 9.7 = <strong>116.5</strong></p>
<p>** <strong>The ratio of right over left is: </strong>116.5<strong>&nbsp; = </strong><em>0.89</em>********</p>
<pre><code>                    **131.0******</code></pre>
<p>Coefficients for a third-degree polynomial are then loaded into the system that allow it to infer a horizontal rotation angle from this ratio. The details for how this is done are given in section 4.4. In the test case, a ratio of 0.89 represents an angle of -16.7 degrees, where the minus sign means the angle is to the left of the normal of the image direction and object plane, in the horizontal plane normal to the object plane:</p>
<p><em>Diagram showing meaning of positive and negative angle values</em></p>
<p><em>[Fig. 4.2.8]</em></p>
<p>The real angle of the images was – to within around 2 degrees of accuracy – 17 degrees, so the estimated value is valid. The prototype determines whether&nbsp; the angle of the camera is acceptable or not. As before, a tolerance value is chosen- this time five degrees- and, clearly, 17 degrees lies outside this tolerance. Thus the code informs the user how far the camera has to be rotated in order for it to be correctly positioned, waits for the user to reposition it and take a new image, and loads the new image.</p>
<p>With the new image, the process repeats again. With the test case, input image, and the mask of the image, are as follows:&nbsp;</p>
<p><em>(a) (b)</em></p>
<p><em>The third input image (a), and its marker mask (b)</em></p>
<p><em>[Fig. 4.2.9]</em></p>
<p>This gives marker positions as follows:</p>
<pre><code>  ****
  ****
  ****


  ******
  
  


  ******
  
  


  ******
  
  


  ******
  
  </code></pre>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Point</th>
<th>x</th>
<th>y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Top Left</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Top Right</td>
<td>189.7</td>
<td>-0.8</td>
</tr>
<tr class="odd">
<td>Bottom Left</td>
<td>0.4</td>
<td>123.4</td>
</tr>
<tr class="even">
<td>Bottom Right</td>
<td>191.8</td>
<td>123.2</td>
</tr>
</tbody>
</table>
<p><em>New relative positions of marker centres</em></p>
<p><em>[Table. 4.2.4]</em></p>
<p>Which gives a ratio of 1.00, which equates to an angle of 1.09 degrees; acceptable for passing to the next stage.</p>
<p><strong><em>Stage 2: Finding Object Disparity</em></strong></p>
<p><strong><em>Introduction</em></strong></p>
<p>Now the camera has been positioned correctly, the prototype needs to determine how far the object (the red rectangle) is displaced from its position in the archive image. In all current (non-archive) images, the object is 6.0mm further to the right, and 4.0mm lower, than it is in the archive image.</p>
<p>In order to determine the disparity of the object, any disparity between the test and archive images as a whole – known as rigid body disparity – needs to be determined. Stage one of the process allows the <em>angle</em> of the camera to be corrected relative to the plane, but does not correct the <em>position</em> along the axes of the plane from which the camera views the bounded area.&nbsp;</p>
<p>Once this rigid body disparity has been found, it can be compensated for when performing a digital image correlation (DIC), so that ‘like’ regions – regions of the images common to both archive and current – can be compared.</p>
<p>An object disparity value found by performing a DIC on the common regions of the pair of images, in pixels, then needs to be converted to a value in millimetres, by using a scale found by comparing real-life boundary marker geometries with those located in pixels.</p>
<p>Thus, stage two essentially involves three sub-stages, each of which will now be detailed for the test case in sequence.</p>
<p><strong><em>Sub-stage 1: Rigid-body Disparity</em></strong></p>
<p>Rigid body disparity, the disparity between two images due to a shift between the images as a whole (rather than displacement of a small-sub region of the image – i.e.&nbsp;the movable object), can be determined in a number of ways:&nbsp;</p>
<p>If the images are of a flat surface with an amorphous (non-repeating) pattern on it – such as wood-chip wallpaper –, and where any movable objects within the image areas occupy only a small image area, and/or of a low intensity within the intensity plane used, then simply performing a DIC of both whole images should produce an output with the greatest intensity peak at the rigid-body displacement position.</p>
<p>There are a number of problems with this approach: A DIC of the whole image will be affected by both rigid body and object disparity, and may produce a results whose peak is at a position that is a ‘compromise’ between the rigid-body displacement (which should have the greatest ‘energy’ in the image, as most of the features of the image match at this disparity position), and the object displacement. Thus it would produce the wrong value for rigid-body disparity.</p>
<p>Also, most machine work surfaces do not have fixed amorphous patterns on them in a region of interest. Consider a work surface on a drilling machine: Originally, its work surface may be shiny and featureless; over time features on the surface may result in the form of scratches and general wear, but these features are likely to change over time - as more scratches are introduced -, and so cannot be used to determine rigid body disparity between two images taken – for instance – months apart.&nbsp;</p>
<p>A better method, therefore, may be to use the boundary markers found in the previous stages. This should be more reliable, as they are strong, already identified features, which are not as subject to change in appearance over time than the region actually within the working area.</p>
<p>Thus, in the test case, the rigid-body disparity is found by comparing the boundary marker masks of the current and archive image, rather than the images themselves.&nbsp;</p>
<p>The image and mask for both the current image and the archive image are as follows:</p>
<p><em>(a) (b)</em></p>
<p><em>The archive image (a) and the current image (b): Note that the lighting is significantly different for both images, but this does not affect the ability for the computer to identify the boundary markers</em></p>
<p><em>[Fig. 4.2.10]</em>**</p>
<p><em>(a) (b)</em></p>
<p><em>The archive mask (a) and the current mask (b): The differences in lighting are compensated for</em></p>
<p><em>[Fig. 4.2.11]</em></p>
<p>This produces the following normalised cross-correlation image:</p>
<p><em>Normalised cross-correlation of the two masks: Note the clarity of the main intensity peak</em></p>
<p><em>[Fig. 4.2.12]</em></p>
<p>The position of the peak is identified at x = -20 pixels, and y = 1 pixel.&nbsp;</p>
<p>This <em>is</em> the <strong><em>rigid body disparity</em></strong> <em>in pixels</em>.</p>
<p><strong><em>Sub-stage 2: Object Disparity</em></strong></p>
<p>Having identified the rigid body disparity, one now needs to identify the displacement of the object <em>within the plane</em>, rather than in the images.</p>
<p>The object is located (almost) exclusively in both images by using the technique given in section 2.3.3, giving the following pair of intensity planes:</p>
<p><em>(a) (b)</em>**</p>
<p><em>Object colour intensity plane images from (a) the archive image and (b) the current image</em></p>
<p><em>[Fig. 4.2.13]</em></p>
<p>The displacement between the objects in these two images could be considered to the sum of the object disparity, and the rigid body disparity. One could simply determine this disparity, and subtract the rigid body disparity from it to obtain the object disparity; or one could use the rigid body information to form <em>rigid-body compensated</em> object images. These images show only the regions of the larger images common to both images:</p>
<p><em>(a) (b)</em>**</p>
<p><em>Rigid-body compensated object intensity planes: These images now show only the regions of the original images common to both; rigid-body disparity has been removed&nbsp;</em></p>
<p><em>[Fig. 4.2.14]</em></p>
<p>These images are 20 pixels (the x-axis RB disparity) smaller in width, and 1 pixel (the y-axis RB disparity) smaller in height. As they are smaller, the region containing the object represents a larger proportion of the total image area, and thus has a stronger presence within the image, and produces a slightly more pronounced peak when DIC is used on it:</p>
<p><em>NCC of the RB compensated object images&nbsp;</em></p>
<p><em>[Fig. 4.2.15]</em></p>
<p>The position of the peak on this NCC graph (Fig. 4.2.15) is x = 15 pixels, and y = 10 pixels.</p>
<p>This is the recorded value of the object disparity.</p>
<p>One can consider how accurate these values seem by comparing them with the actual object displacement: 6.0mm to the right, and 4.0mm downward. Due to the way Matlab stores images, the origin is taken as the top left corner, thus displacements to the right, and downward, are both positive displacements. Both the x and y object displacement values are positive, which means the recorded object displacement is in the correct direction.&nbsp;</p>
<p>The ratio between x displacement and y displacement in both cases (actual in mm, and recorded in pixels) is 3/2 (15pixels/10pixels = 6mm/4mm = 3/2), again suggesting that the displacement value found is accurate.</p>
<p><strong><em>Sub-stage 3: Real-life Disparity</em></strong></p>
<p>The final stage involves converting the pixel disparities into millimetre disparities, by finding the ratio between pixels and millimetres.</p>
<p>The locations of the marker centres on the current image are as follows:</p>
<pre><code>  ****
  ****
  ****


  ******
  
  


  ******
  
  


  ******
  
  


  ******
  
  </code></pre>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Point</th>
<th>x</th>
<th>y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Top Left</td>
<td>68.1</td>
<td>54.5</td>
</tr>
<tr class="even">
<td>Top Right</td>
<td>257.8</td>
<td>53.7</td>
</tr>
<tr class="odd">
<td>Bottom Left</td>
<td>68.5</td>
<td>177.9</td>
</tr>
<tr class="even">
<td>Bottom Right</td>
<td>259.9</td>
<td>177.7</td>
</tr>
</tbody>
</table>
<p><em>Positions of marker centres – in pixels</em></p>
<p><em>[Table. 4.2.5]</em>**</p>
<p>The position of the two horizontal edges – Top right (x) less top left (x), and bottom right (x) less bottom left (x) – are not exactly the same, so a mean is used, to provide an average horizontal edge length in pixels. The same is done with the two vertical edges, giving a horizontal edge value of 190.5 pixels, and a vertical edge value of 123.7 pixels.</p>
<p>From the data provided at the start on real geometry, the real vertical edge distance is 70.0mm, and the vertical edge distance is 50.0mm. Dividing real edge distance by pixel edge distances gives a vertical ratio of 0.40 mm per pixel, and a horizontal ratio of 0.37 mm per pixel. These figures could be thought of as representing the system <em>resolution</em>, without resorting to sub-pixel algorithms.</p>
<p>Multiplying the pixel disparities by these ratios gives real-life disparity estimates of 5.5mm (actual: 6.0mm) horizontally, and 4.0mm (actual: 4.0mm) vertically. This gives an overall magnitude of displacement of 6.8mm (actual 7.2mm). Thus the disparity values are accurate to within half a millimetre of the true value, in both the horizontal and vertical axes.</p>
<p>The bounded object plane area was 70.0mm x 50.0mm, or 3500.0mm<sup>2</sup>; the object displacement figure found was accurate to ±0.5mm<sup>2</sup> (The square root of 0.5<sup>2</sup> + 0.0<sup>2</sup>). This gives a calculated accuracy level to within 0.5 / 3500, or 0.14 per <strong><em>mil</em></strong><em>.</em> Using the 0.40 and 0.37 mm / pixel resolution figures calculated earlier gives a displacement determination accuracy of ±0.54mm<sup>2</sup>, the same value to 1 significant figure.&nbsp;</p>
<p><strong><em>Other Examples</em></strong></p>
<p><strong><em>Introduction</em></strong></p>
<p>Though the example given in the previous section shows how the processes work, it does not show how the processes operate in other conditions.</p>
<p><strong><em>Effect Of Non-critical Objects On Identification Of Critical Objects</em></strong></p>
<p>In the prototype, two types of object need to be identified: those that mark the boundaries of the area of interest, and the movable object of interest. These are identified by colour. Below, three examples are given where camera position, and movable object of interest are fixed, but other objects – of a non-specified colour – differ in position:</p>
<p><em>Test Image 1 Marker Mask Object Mask</em></p>
<p><em>[Fig. 4.3.1]</em>**</p>
<p><em>Test Image 2 Marker Mask Object Mask</em></p>
<p><em>[Fig. 4.3.2]</em>**</p>
<p><em>Test Image 3 Marker Mask Object Mask</em></p>
<p><em>[Fig. 4.3.3]</em>**</p>
<p>In two of the three cases, the system is able to identify both the markers and the movable object exclusively, without any difficulty. In the third image (Fig 4.3.3), part of a shadow formed by one of the non-critical objects is of a colour and intensity (black), and of a significant enough size, to be wrongly identified as part of a marker. This is a problem specific to greyscale (rather than colour) markers, and again highlights why colour marker colours are often used (Note that the object mask, of a vivid red colour, was successfully and exclusively identified in all three cases). Even this erroneously included portion of the feature could be successfully identified as erroneous by the computer and removed by, for instance, further erosion filtering, or simply (as, in the prototype case, there are just four markers) retaining only the largest object in each quarter of the mask.&nbsp;</p>
<p>Where erroneously identified objects exist that are of similar or greater size to the correctly identified mask features, a more complicated system - that, for example, determines which of the feature objects identified in the mask is <em>most likely</em> to be the real one based on the known marker geometry – would have to be used.</p>
<p><strong><em>Effects Of Lighting</em></strong></p>
<p>So far, all examples shown have been ones where ambient lighting has been of a normal level; the image was neither dark nor light, and the camera neither over exposed or underexposed. The following images show some of the effects of different types of ambient lighting conditions, including many which are sub-optimal:</p>
<p><em>Test Image 1 Marker Mask Object Mask</em></p>
<p><em>[Fig. 4.3.4]</em></p>
<p><em>Test Image 2 Marker Mask Object Mask</em></p>
<p><em>[Fig. 4.3.5]</em>**</p>
<p><em>Test Image 3 Marker Mask Object Mask</em></p>
<p><em>[Fig. 4.3.6]</em>**</p>
<p><em>Test Image 4 Marker Mask Object Mask</em></p>
<p><em>[Fig. 4.3.7]</em>**</p>
<p><em>Test Image 5 Marker Mask Object Mask</em></p>
<p><em>[Fig. 4.3.8]</em>**</p>
<p><em>Test Image 6 Marker Mask Object Mask</em></p>
<p><em>[Fig. 4.3.9]</em>**</p>
<p>A table summarising image descriptions and results is as follows:</p>
<pre><code>  ****
  ****
  ****
  ****
  ****


  ****
  **
  ******
  ******
  **


  ****
  **
  ********
  ******
  **



  ****
  ****
  **********

  ******
  **



  ****
  ****
  ******
  **********
  **


  ****
  ****
  ********
  ********
  **


  ****
  **
  ********
  ******
  **</code></pre>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Image Number</th>
<th>Description</th>
<th>Marker Identification</th>
<th>Object Identification</th>
<th>Comment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Normal, constant ambient lighting.</td>
<td>OK</td>
<td>OK</td>
<td>Control Case</td>
</tr>
<tr class="even">
<td>2</td>
<td>Dark /underexposed. Even/ constant lighting.</td>
<td>Not OK – Three erroneous features. Not connected to correct features</td>
<td>OK</td>
<td></td>
</tr>
<tr class="odd">
<td>3</td>
<td>Dark/ underexposed.</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Uneven lighting.</td>
<td>Not OK – four erroneous features. One connected to marker object</td>
<td>OK</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>4</td>
<td>Overexposed/ bright.</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Even lighting (directly from behind)</td>
<td>OK</td>
<td>Not OK –&nbsp;</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Not identified</td>
<td>Marker mask is sharp</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>5</td>
<td>Overexposed/ bright.</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Uneven lighting (from bottom left hand side)</td>
<td>Not OK – One feature erroneously identified</td>
<td>Not OK – Object correctly identified, but brightest corner of image also erroneously identified as image</td>
<td>Objects connected to image corner or edge can be identified as erroneous and removed</td>
<td></td>
</tr>
<tr class="even">
<td>6</td>
<td>Uneven lighting, partially bright, partially dark</td>
<td>Not OK – One feature erroneously identified</td>
<td>OK</td>
<td></td>
</tr>
</tbody>
</table>
<p><em>Table of lighting effects on object identification</em></p>
<p><em>[Table. 4.3.1]</em>**</p>
<p>As stated previously, using a greyscale marker represents a worst-case scenario regarding ease of identification. This shows in these results, where the shadow formed by one particular non-critical object, near the top right of the bounded area, is erroneously identified in almost every marker mark of the image with sub-optimal lighting. In images 2 and 3, even more objects are included erroneously. In no cases, however, are the correct objects not <em>identified,</em> and only in image 3 does an erroneous feature ‘bleed’ into a marker (making removing erroneous features exclusively more difficult).&nbsp;</p>
<p>In comparison, the red object was correctly and exclusively identified in almost all cases. When the camera was greatly overexposed (Image 4), the program was unable to differentiate between the object and its background, and thus it was not identified. In the other case (Image 5), part of the edge of the image was overexposed, and incorrectly identified. However, as the object is known to not be on the edge of the image, and the erroneous feature was not connected to it, the erroneous feature could identified as such and removed quite easily.</p>
<p>The results of image 4 are important, as, in this case, the markers were easily identified. This type of image could be created by either increasing the contrast of the camera, or by switching on a portable light source behind the camera. This would have the effect of removing the effect of uneven lighting on creating erroneous feature identification (such as in image 5), and more easily than attempting to <em>block</em> light. Afterwards, the light source could be de-activated to allow the red object to be identified.</p>
<p>In a more general case, a strong light source that makes features of a certain colour more prominent could be used to make identifying that particular feature easier.</p>
<p><strong><em>Effects Of Camera Distance</em></strong></p>
<p>So far, all tests have been conducted at a single distance (154mm). The following table shows the effect changing the distance has on the calculated ratio of right side vertical distance between markers to left side distance- used to calculate the horizontal plane angle of the camera to the object plane – at 30 degrees to the left of the normal angle.&nbsp;</p>
<pre><code>  ****
  ****
  ****


  ******
  
  


  ******
  
  


  ******
  
  


  ******
  
  


  ******
  
  


  ******
  
  </code></pre>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Distance (mm)</th>
<th>Ratio (RHS / LHS)</th>
<th>Relative Ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>154</td>
<td>0.86</td>
<td>1.00</td>
</tr>
<tr class="even">
<td>174</td>
<td>0.87</td>
<td>1.02</td>
</tr>
<tr class="odd">
<td>194</td>
<td>0.88</td>
<td>1.03</td>
</tr>
<tr class="even">
<td>214</td>
<td>0.89</td>
<td>1.03</td>
</tr>
<tr class="odd">
<td>234</td>
<td>0.89</td>
<td>1.04</td>
</tr>
<tr class="even">
<td>254</td>
<td>0.90</td>
<td>1.05</td>
</tr>
</tbody>
</table>
<p><em>Table of effect of distance on calculated ratio</em></p>
<p><em>[Table. 4.3.2]</em></p>
<p><em>Masks used to calculate ratios at same angle and different distances</em></p>
<p><em>[Fig. 4.3.10]</em>**</p>
<p>As one can see, as the distance increases, the ratio tends towards 1. This makes sense due to the effects a limited resolution has on the way an object is interpreted at different distances. As the object gets further away, more information about it is lost, and less can be interpreted about it. Even looking at the masks of the images, they start to appear more rectangular when smaller, and this effect is resulting in the increasingly inaccurate ratio results.</p>
<p>It would be possible to use the actual number of pixels between markers, and the size of markers in the images, to estimate the distance from the camera to the plane, and thus the accuracy of other figures such as estimated angle.&nbsp;</p>
<p>In DIC, is important that the two images to be correlated are at the same distance (as well as angle). Thus, a final system would need to be able to determine and inform the user of its distance from the plane, as well as angle to it. &nbsp;</p>
<p><strong><em>4.4 Calibration</em></strong></p>
<p>For stage 1b, it was required that the prototype device be able to determine an angle from a ratio. This required prior calibration: 10 sets of 17 images, at a set distance and horizontal plane angles varying incrementally from –40 degrees to 40 degrees in 5 degree steps, were taken, and the ratio between left vertical edge and right vertical edge (as in the previous example) were found.&nbsp;</p>
<p>The average value at each of these angles, from all 10 cases, was found, giving the following results when plotted against angle:</p>
<p><em>Graph of ratio to angle</em></p>
<p><em>[Fig. 4.4.1]</em></p>
<p>A third degree polynomial approximation, equating ratio to angle, was found, and the coefficients generated stored. The Matlab functions <em>polyfit </em>and <em>polytool</em> were used, and the red lines on the above graph show the <em>polytool</em> estimated error level of the polynomial fit to the real values. These are loaded into the stage 1b code, and used to calculate the horizontal plane angle.</p>
<p>The coefficients, in descending order, are: <strong>272.6; &nbsp; -914.3; 1,152.0; &nbsp; -509.9</strong></p>
<p>i.e.&nbsp;<span class="eqn-ref"><em>equation</em></span> <em>[Eqn. 4.4.1]</em></p>
<p>As an example, the ratio value 1.08 (r = 1.08) leads to an angle (θ) estimate of 11.2 degrees. Using r = 1.04 yields θ = 5.9 degrees.</p>
<p><em>Negative angle</em></p>
<p><em>Positive angle</em></p>
<p><strong>Object plane</strong></p>


<!-- -->


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/jonminton\.github\.io\/academic-works");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb10" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Results"</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>4</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>**&nbsp;Results**</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>***4.1  Section Introduction***</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>This section provides results attained through the use and creation of the prototype system. It is split into three sub-sections:&nbsp;</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>Results of all processes to a single test example.</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>Results of various processes to other example inputs.</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>Results required for machine calibration and testing system stability.</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>***Results Of System Using Single Test Case***</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>***Introduction***</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>Here, the stages of the prototype system listed in section 3 are demonstrated using a single test case.</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>In the test case, the bounded area was a rectangle 70mm wide and 50 mm high. This was marked out using four black square blocks 10 mm wide. Black was used as the marker colour as it is a poor choice of marker colour (due to the reasons given in section 2.3.2), and so demonstrating that the system works with this colour scheme suggest that it should also work with others (where the affect of bright lights and shadows can be more easily mitigated).</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a>The object is represented by a small movable red rectangle 8mm wide and 6 mm high. Am image of this object within the bounded area, at the ‘correct’ position, is taken, and loaded, as an archived image, into the system at the start of the program sequence:</span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>*Archive image of marker object (red rectangle) in correct position*</span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.2.1]*</span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a>Note that, within the bounded area, other objects, of a different colour, also exist. To work, the prototype system should not be affected by the position of these other objects. The background is graph paper, which, as a repeating pattern, creates ‘noise’ when a DIC approach is used (due to localised areas of image correlation). Both of these factors make the test case good for demonstrating the rigorousness of the system.</span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a>The geometry of the markers is also entered into the system at the start. The position of the four markers, from each other and in millimetres, is loaded into the system as the following 4 x 2 element array:</span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-45"><a href="#cb10-45" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-46"><a href="#cb10-46" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-47"><a href="#cb10-47" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-48"><a href="#cb10-48" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-49"><a href="#cb10-49" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-50"><a href="#cb10-50" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-51"><a href="#cb10-51" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-52"><a href="#cb10-52" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-53"><a href="#cb10-53" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-54"><a href="#cb10-54" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-55"><a href="#cb10-55" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-56"><a href="#cb10-56" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-57"><a href="#cb10-57" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-58"><a href="#cb10-58" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-59"><a href="#cb10-59" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-60"><a href="#cb10-60" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-61"><a href="#cb10-61" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-62"><a href="#cb10-62" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-63"><a href="#cb10-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-64"><a href="#cb10-64" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb10-65"><a href="#cb10-65" aria-hidden="true" tabindex="-1"></a><span class="pp">| ---</span> <span class="pp">| ---</span> <span class="pp">|</span></span>
<span id="cb10-66"><a href="#cb10-66" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 70 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb10-67"><a href="#cb10-67" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 0 <span class="pp">|</span> 50 <span class="pp">|</span></span>
<span id="cb10-68"><a href="#cb10-68" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 70 <span class="pp">|</span> 50 <span class="pp">|</span></span>
<span id="cb10-69"><a href="#cb10-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-70"><a href="#cb10-70" aria-hidden="true" tabindex="-1"></a>*Marker position matrix used*</span>
<span id="cb10-71"><a href="#cb10-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-72"><a href="#cb10-72" aria-hidden="true" tabindex="-1"></a>*[Table. 4.2.1]*</span>
<span id="cb10-73"><a href="#cb10-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-74"><a href="#cb10-74" aria-hidden="true" tabindex="-1"></a>Where the first column gives the horizontal distance from the origin, and the second gives the vertical distance from the origin.</span>
<span id="cb10-75"><a href="#cb10-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-76"><a href="#cb10-76" aria-hidden="true" tabindex="-1"></a>Also given are information on the colour combination to use to find both the object marker (red), and the boundary markers (black). In the case of the boundary marker, this would be an instruction to convert the colour image into a greyscale image (by combining the pixel average of the three colour intensity plane) and then inverting, so dark areas become areas of high intensity. In the case of the red object marker, the procedure shown in section 2.3.3 is used.&nbsp;</span>
<span id="cb10-77"><a href="#cb10-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-78"><a href="#cb10-78" aria-hidden="true" tabindex="-1"></a>The physical apparatus used for the test is as follows: A webcam is fixed to a certain position on ruler. The head of the webcam is fixed, vertically aligned with reference to its base, and facing forwards in the direction parallel to that of the ruler. At the end of the ruler a small cocktail is attached, propagating from the centre of the ruler width a small distance beyond that of the ruler. This provides a thin fulcrum about which the camera may rotate in the horizontal plane normal to the object plane, which is one of the walls of the room.&nbsp;</span>
<span id="cb10-79"><a href="#cb10-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-80"><a href="#cb10-80" aria-hidden="true" tabindex="-1"></a>*Image of the camera apparatus used*</span>
<span id="cb10-81"><a href="#cb10-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-82"><a href="#cb10-82" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.2.2]***</span>
<span id="cb10-83"><a href="#cb10-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-84"><a href="#cb10-84" aria-hidden="true" tabindex="-1"></a>The ruler is rested on the top of a table that is horizontally balanced with the markers on the object plane, and at a height such that the camera image is at the same height as the bounded area of the object plane. This reduces the number of positional factors that need to be considered, and that the effect of a single variable can be more easily isolated.&nbsp;</span>
<span id="cb10-85"><a href="#cb10-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-86"><a href="#cb10-86" aria-hidden="true" tabindex="-1"></a>***Stage 1a: Finding Rotation Parallel To Plane***</span>
<span id="cb10-87"><a href="#cb10-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-88"><a href="#cb10-88" aria-hidden="true" tabindex="-1"></a>***Determining Centres Of Markers***</span>
<span id="cb10-89"><a href="#cb10-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-90"><a href="#cb10-90" aria-hidden="true" tabindex="-1"></a>If, to begin with, the camera image is at both the wrong angle in the plane parallel to the image, and horizontally perpendicular to it, then its position can be corrected one stage at time. To begin with, the angle of rotation parallel to the image plane is compensated found.</span>
<span id="cb10-91"><a href="#cb10-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-92"><a href="#cb10-92" aria-hidden="true" tabindex="-1"></a>In the test example, the first image entered into the prototype system was as shown below on the left. The prototype first identified the boundary markers as shown below on the right:</span>
<span id="cb10-93"><a href="#cb10-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-94"><a href="#cb10-94" aria-hidden="true" tabindex="-1"></a>*The first camera image (left) and the marker mask of the image (right)*</span>
<span id="cb10-95"><a href="#cb10-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-96"><a href="#cb10-96" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.2.3]*</span>
<span id="cb10-97"><a href="#cb10-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-98"><a href="#cb10-98" aria-hidden="true" tabindex="-1"></a>Four sub-masks are then formed from this mask, effectively splitting the mask up into four quarters. The sub-masks are adjusted such that the corner of the quarter is at the origin of the sub-mask (e.g. for the bottom right quarter, the sub-image is flipped horizontally and vertically; for the top right quarter, the image is just flipped horizontally).</span>
<span id="cb10-99"><a href="#cb10-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-100"><a href="#cb10-100" aria-hidden="true" tabindex="-1"></a>The co-ordinates of the centres of mass (and thus the central points of each marker) of each quarter are then located using the method described in section 2.3.4, giving the co-ordinates of the centre of the image from the corner of the image it is closest to:</span>
<span id="cb10-101"><a href="#cb10-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-102"><a href="#cb10-102" aria-hidden="true" tabindex="-1"></a>*(a)            (b)         (c)         (d)*</span>
<span id="cb10-103"><a href="#cb10-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-104"><a href="#cb10-104" aria-hidden="true" tabindex="-1"></a>*Sub-masks of the (a) top left, (b) top right, (c) bottom left, and (d) bottom right quarters of the mask image*</span>
<span id="cb10-105"><a href="#cb10-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-106"><a href="#cb10-106" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.2.4]*</span>
<span id="cb10-107"><a href="#cb10-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-108"><a href="#cb10-108" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-109"><a href="#cb10-109" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-110"><a href="#cb10-110" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-111"><a href="#cb10-111" aria-hidden="true" tabindex="-1"></a><span class="in">      **************</span></span>
<span id="cb10-112"><a href="#cb10-112" aria-hidden="true" tabindex="-1"></a><span class="in">      **************</span></span>
<span id="cb10-113"><a href="#cb10-113" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-114"><a href="#cb10-114" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-115"><a href="#cb10-115" aria-hidden="true" tabindex="-1"></a><span class="in">      **</span></span>
<span id="cb10-116"><a href="#cb10-116" aria-hidden="true" tabindex="-1"></a><span class="in">      **</span></span>
<span id="cb10-117"><a href="#cb10-117" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-118"><a href="#cb10-118" aria-hidden="true" tabindex="-1"></a><span class="in">      **</span></span>
<span id="cb10-119"><a href="#cb10-119" aria-hidden="true" tabindex="-1"></a><span class="in">      **</span></span>
<span id="cb10-120"><a href="#cb10-120" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-121"><a href="#cb10-121" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-122"><a href="#cb10-122" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-123"><a href="#cb10-123" aria-hidden="true" tabindex="-1"></a><span class="in">      **</span></span>
<span id="cb10-124"><a href="#cb10-124" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-125"><a href="#cb10-125" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-126"><a href="#cb10-126" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-127"><a href="#cb10-127" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-128"><a href="#cb10-128" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-129"><a href="#cb10-129" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-130"><a href="#cb10-130" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-131"><a href="#cb10-131" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-132"><a href="#cb10-132" aria-hidden="true" tabindex="-1"></a><span class="in">      **</span></span>
<span id="cb10-133"><a href="#cb10-133" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-134"><a href="#cb10-134" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-135"><a href="#cb10-135" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-136"><a href="#cb10-136" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-137"><a href="#cb10-137" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-138"><a href="#cb10-138" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-139"><a href="#cb10-139" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-140"><a href="#cb10-140" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-141"><a href="#cb10-141" aria-hidden="true" tabindex="-1"></a><span class="in">      **</span></span>
<span id="cb10-142"><a href="#cb10-142" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-143"><a href="#cb10-143" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-144"><a href="#cb10-144" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-145"><a href="#cb10-145" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-146"><a href="#cb10-146" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-147"><a href="#cb10-147" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-148"><a href="#cb10-148" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-149"><a href="#cb10-149" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-150"><a href="#cb10-150" aria-hidden="true" tabindex="-1"></a><span class="in">      **</span></span>
<span id="cb10-151"><a href="#cb10-151" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-152"><a href="#cb10-152" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-153"><a href="#cb10-153" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-154"><a href="#cb10-154" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-155"><a href="#cb10-155" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-156"><a href="#cb10-156" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-157"><a href="#cb10-157" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-158"><a href="#cb10-158" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-159"><a href="#cb10-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-160"><a href="#cb10-160" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Quarter <span class="pp">|</span> Horizontal distance… (in pixels) <span class="pp">|</span> Vertical distance… (in pixels) <span class="pp">|</span></span>
<span id="cb10-161"><a href="#cb10-161" aria-hidden="true" tabindex="-1"></a><span class="pp">| ---</span> <span class="pp">| ---</span> <span class="pp">| ---</span> <span class="pp">|</span></span>
<span id="cb10-162"><a href="#cb10-162" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> To start of marker block <span class="pp">|</span> To centre of marker block <span class="pp">|</span> From corner <span class="pp">|</span> To start of marker block <span class="pp">|</span> To centre of marker block <span class="pp">|</span> From corner <span class="pp">|</span></span>
<span id="cb10-163"><a href="#cb10-163" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Top Left <span class="pp">|</span> 74 <span class="pp">|</span> 20.6 <span class="pp">|</span> 94.6 <span class="pp">|</span> 29 <span class="pp">|</span> 19.8 <span class="pp">|</span> 48.8 <span class="pp">|</span></span>
<span id="cb10-164"><a href="#cb10-164" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Top Right <span class="pp">|</span> 28 <span class="pp">|</span> 16.2 <span class="pp">|</span> 44.2 <span class="pp">|</span> 53 <span class="pp">|</span> 18.8 <span class="pp">|</span> 71.8 <span class="pp">|</span></span>
<span id="cb10-165"><a href="#cb10-165" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Bottom Left <span class="pp">|</span> 60 <span class="pp">|</span> 20.9 <span class="pp">|</span> 80.9 <span class="pp">|</span> 43 <span class="pp">|</span> 19.3 <span class="pp">|</span> 62.3 <span class="pp">|</span></span>
<span id="cb10-166"><a href="#cb10-166" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Bottom Right <span class="pp">|</span> 37 <span class="pp">|</span> 17.6 <span class="pp">|</span> 54.6 <span class="pp">|</span> 32 <span class="pp">|</span> 18.4 <span class="pp">|</span> 50.4 <span class="pp">|</span></span>
<span id="cb10-167"><a href="#cb10-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-168"><a href="#cb10-168" aria-hidden="true" tabindex="-1"></a>*Table of centre point positions calculated*</span>
<span id="cb10-169"><a href="#cb10-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-170"><a href="#cb10-170" aria-hidden="true" tabindex="-1"></a>*[Table. 4.2.2]***</span>
<span id="cb10-171"><a href="#cb10-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-172"><a href="#cb10-172" aria-hidden="true" tabindex="-1"></a>&nbsp;</span>
<span id="cb10-173"><a href="#cb10-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-174"><a href="#cb10-174" aria-hidden="true" tabindex="-1"></a>These results are used to determine the following co-ordinate positions for the centre of the markers in the image as a whole:</span>
<span id="cb10-175"><a href="#cb10-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-176"><a href="#cb10-176" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-177"><a href="#cb10-177" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-178"><a href="#cb10-178" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-179"><a href="#cb10-179" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-180"><a href="#cb10-180" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-181"><a href="#cb10-181" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-182"><a href="#cb10-182" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-183"><a href="#cb10-183" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-184"><a href="#cb10-184" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-185"><a href="#cb10-185" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-186"><a href="#cb10-186" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-187"><a href="#cb10-187" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-188"><a href="#cb10-188" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-189"><a href="#cb10-189" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-190"><a href="#cb10-190" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-191"><a href="#cb10-191" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-192"><a href="#cb10-192" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-193"><a href="#cb10-193" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-194"><a href="#cb10-194" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-195"><a href="#cb10-195" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-196"><a href="#cb10-196" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-197"><a href="#cb10-197" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-198"><a href="#cb10-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-199"><a href="#cb10-199" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> x <span class="pp">|</span> y <span class="pp">|</span></span>
<span id="cb10-200"><a href="#cb10-200" aria-hidden="true" tabindex="-1"></a><span class="pp">| ---</span> <span class="pp">| ---</span> <span class="pp">|</span></span>
<span id="cb10-201"><a href="#cb10-201" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 94.6 <span class="pp">|</span> 48.8 <span class="pp">|</span></span>
<span id="cb10-202"><a href="#cb10-202" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 275.8 <span class="pp">|</span> 71.8 <span class="pp">|</span></span>
<span id="cb10-203"><a href="#cb10-203" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 80.9 <span class="pp">|</span> 177.7 <span class="pp">|</span></span>
<span id="cb10-204"><a href="#cb10-204" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 265.4 <span class="pp">|</span> 189.6 <span class="pp">|</span></span>
<span id="cb10-205"><a href="#cb10-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-206"><a href="#cb10-206" aria-hidden="true" tabindex="-1"></a>*Coordinates of the centres of the markers, in pixels*</span>
<span id="cb10-207"><a href="#cb10-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-208"><a href="#cb10-208" aria-hidden="true" tabindex="-1"></a>*[Table. 4.2.3]***</span>
<span id="cb10-209"><a href="#cb10-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-210"><a href="#cb10-210" aria-hidden="true" tabindex="-1"></a>These positions are represented on the image below as the red points on the greyscale version of the input image, and the mask used to calculate them:</span>
<span id="cb10-211"><a href="#cb10-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-212"><a href="#cb10-212" aria-hidden="true" tabindex="-1"></a>*(a)                    (b)*</span>
<span id="cb10-213"><a href="#cb10-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-214"><a href="#cb10-214" aria-hidden="true" tabindex="-1"></a><span class="ss">*&nbsp; </span>Coordinates of the centres of the markers, superimposed (a) on mask, and (b) on greyscale version of input image*</span>
<span id="cb10-215"><a href="#cb10-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-216"><a href="#cb10-216" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.2.5]***</span>
<span id="cb10-217"><a href="#cb10-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-218"><a href="#cb10-218" aria-hidden="true" tabindex="-1"></a>&nbsp; &nbsp;</span>
<span id="cb10-219"><a href="#cb10-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-220"><a href="#cb10-220" aria-hidden="true" tabindex="-1"></a>***Determining Rotation***</span>
<span id="cb10-221"><a href="#cb10-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-222"><a href="#cb10-222" aria-hidden="true" tabindex="-1"></a>It is now relatively simple to determine the plane-parallel rotation of the camera to the object plane. The process is as follows:</span>
<span id="cb10-223"><a href="#cb10-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-224"><a href="#cb10-224" aria-hidden="true" tabindex="-1"></a>Compare the vertical distance between the two points on the left (Left half of image), with the two points on the right (Right half of image). The camera is closer to the side whose points are further apart. In the test case, the two points on the left are further apart.</span>
<span id="cb10-225"><a href="#cb10-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-226"><a href="#cb10-226" aria-hidden="true" tabindex="-1"></a>The points from this half are more accurate representations of the centres of the markers, as the camera is closer to them, and thus their effective resolution in the image is higher. Due to the way the markers are formed, borderlines of a certain number of pixels are created which extend slightly beyond the boundaries of the marker in the original image (Fig. 2.3.10; Fig 2.3.11). The distortion of the marker shape and position due to these borderlines are greater if the marker is smaller; thus the larger (in this case closer) markers provide more accurate estimates of their central positions. These two position co-ordinates on the left side are considered thus those used to determine the angle.</span>
<span id="cb10-227"><a href="#cb10-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-228"><a href="#cb10-228" aria-hidden="true" tabindex="-1"></a>The horizontal displacement between the two points is divided by the vertical displacement, and the tangent of this value if found to determine the angle between the two markers.</span>
<span id="cb10-229"><a href="#cb10-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-230"><a href="#cb10-230" aria-hidden="true" tabindex="-1"></a>If the angle is small (less than one degree in magnitude, in the case of the prototype), then the program passes to the next stage. Otherwise, the angle between the two points is given to the user, together with instructions on what action to take. In the test case, the first input image yields and angle of –6.1 degrees (due to the way positive and negative displacement is defined, and the instruction:&nbsp;</span>
<span id="cb10-231"><a href="#cb10-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-232"><a href="#cb10-232" aria-hidden="true" tabindex="-1"></a>Rotate Camera in parallel with plane:</span>
<span id="cb10-233"><a href="#cb10-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-234"><a href="#cb10-234" aria-hidden="true" tabindex="-1"></a>6.1</span>
<span id="cb10-235"><a href="#cb10-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-236"><a href="#cb10-236" aria-hidden="true" tabindex="-1"></a>degrees anticlockwise</span>
<span id="cb10-237"><a href="#cb10-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-238"><a href="#cb10-238" aria-hidden="true" tabindex="-1"></a><span class="in">    is given to the user.</span></span>
<span id="cb10-239"><a href="#cb10-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-240"><a href="#cb10-240" aria-hidden="true" tabindex="-1"></a>The prototype now waits for the user to reposition the camera, and take a second image. When the user indicates, the prototype loads in the new image, and performs the same analysis on this as it did on the first. In the test case, the new image was:</span>
<span id="cb10-241"><a href="#cb10-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-242"><a href="#cb10-242" aria-hidden="true" tabindex="-1"></a>*Second (position adjusted) image*</span>
<span id="cb10-243"><a href="#cb10-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-244"><a href="#cb10-244" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.2.6]***</span>
<span id="cb10-245"><a href="#cb10-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-246"><a href="#cb10-246" aria-hidden="true" tabindex="-1"></a>This time, the plane-parallel angle was within the one degree acceptable limit (Calculated as –0.3 degrees), yielding the following output:</span>
<span id="cb10-247"><a href="#cb10-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-248"><a href="#cb10-248" aria-hidden="true" tabindex="-1"></a>Rotational Angle OK</span>
<span id="cb10-249"><a href="#cb10-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-250"><a href="#cb10-250" aria-hidden="true" tabindex="-1"></a>The program now passes the image to the next stage.</span>
<span id="cb10-251"><a href="#cb10-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-252"><a href="#cb10-252" aria-hidden="true" tabindex="-1"></a>***Stage 1b: Finding Horizontal Rotation Normal To Plane***</span>
<span id="cb10-253"><a href="#cb10-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-254"><a href="#cb10-254" aria-hidden="true" tabindex="-1"></a>The next stage is to correct the angle of the camera in the horizontal plane normal to the object plane. The process is as follows:</span>
<span id="cb10-255"><a href="#cb10-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-256"><a href="#cb10-256" aria-hidden="true" tabindex="-1"></a>A mask of the image is created:</span>
<span id="cb10-257"><a href="#cb10-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-258"><a href="#cb10-258" aria-hidden="true" tabindex="-1"></a>*Mask of second image*</span>
<span id="cb10-259"><a href="#cb10-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-260"><a href="#cb10-260" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.2.7]***</span>
<span id="cb10-261"><a href="#cb10-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-262"><a href="#cb10-262" aria-hidden="true" tabindex="-1"></a>and the centres of each of the markers are found using the method detailed in section 4.2.2.1.&nbsp;</span>
<span id="cb10-263"><a href="#cb10-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-264"><a href="#cb10-264" aria-hidden="true" tabindex="-1"></a>The vertical distances between the top left and the bottom left, and the top right and bottom right, marker points are found, and the ratio between them is found. In the test case, the positions of the centres of the four points, with respect to the top left point, are:</span>
<span id="cb10-265"><a href="#cb10-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-266"><a href="#cb10-266" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-267"><a href="#cb10-267" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-268"><a href="#cb10-268" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-269"><a href="#cb10-269" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-270"><a href="#cb10-270" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-271"><a href="#cb10-271" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-272"><a href="#cb10-272" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-273"><a href="#cb10-273" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-274"><a href="#cb10-274" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-275"><a href="#cb10-275" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-276"><a href="#cb10-276" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-277"><a href="#cb10-277" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-278"><a href="#cb10-278" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-279"><a href="#cb10-279" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-280"><a href="#cb10-280" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-281"><a href="#cb10-281" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-282"><a href="#cb10-282" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-283"><a href="#cb10-283" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-284"><a href="#cb10-284" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-285"><a href="#cb10-285" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-286"><a href="#cb10-286" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-287"><a href="#cb10-287" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-288"><a href="#cb10-288" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-289"><a href="#cb10-289" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-290"><a href="#cb10-290" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-291"><a href="#cb10-291" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-292"><a href="#cb10-292" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-293"><a href="#cb10-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-294"><a href="#cb10-294" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Point <span class="pp">|</span> x <span class="pp">|</span> y <span class="pp">|</span></span>
<span id="cb10-295"><a href="#cb10-295" aria-hidden="true" tabindex="-1"></a><span class="pp">| ---</span> <span class="pp">| ---</span> <span class="pp">| ---</span> <span class="pp">|</span></span>
<span id="cb10-296"><a href="#cb10-296" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Top Left <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb10-297"><a href="#cb10-297" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Top Right <span class="pp">|</span> 179.8 <span class="pp">|</span> 9.7 <span class="pp">|</span></span>
<span id="cb10-298"><a href="#cb10-298" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Bottom Left <span class="pp">|</span> -0.7 <span class="pp">|</span> 131.0 <span class="pp">|</span></span>
<span id="cb10-299"><a href="#cb10-299" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Bottom Right <span class="pp">|</span> 182.0 <span class="pp">|</span> 126.2 <span class="pp">|</span></span>
<span id="cb10-300"><a href="#cb10-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-301"><a href="#cb10-301" aria-hidden="true" tabindex="-1"></a>*Relative positions of marker centres*</span>
<span id="cb10-302"><a href="#cb10-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-303"><a href="#cb10-303" aria-hidden="true" tabindex="-1"></a>*[Table. 4.2.4]***</span>
<span id="cb10-304"><a href="#cb10-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-305"><a href="#cb10-305" aria-hidden="true" tabindex="-1"></a>The left side vertical value is thus:   131.0 – 0   =   **131.0**   </span>
<span id="cb10-306"><a href="#cb10-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-307"><a href="#cb10-307" aria-hidden="true" tabindex="-1"></a><span class="in">&nbsp;   And the right side vertical value is:   126.2 – 9.7 =   **116.5**</span></span>
<span id="cb10-308"><a href="#cb10-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-309"><a href="#cb10-309" aria-hidden="true" tabindex="-1"></a>**  **The ratio of right over left is:      **116.5**&nbsp;      =   ***0.89*********</span>
<span id="cb10-310"><a href="#cb10-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-311"><a href="#cb10-311" aria-hidden="true" tabindex="-1"></a><span class="in">                        **131.0******</span></span>
<span id="cb10-312"><a href="#cb10-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-313"><a href="#cb10-313" aria-hidden="true" tabindex="-1"></a>Coefficients for a third-degree polynomial are then loaded into the system that allow it to infer a horizontal rotation angle from this ratio. The details for how this is done are given in section 4.4. In the test case, a ratio of 0.89 represents an angle of -16.7 degrees, where the minus sign means the angle is to the left of the normal of the image direction and object plane, in the horizontal plane normal to the object plane:</span>
<span id="cb10-314"><a href="#cb10-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-315"><a href="#cb10-315" aria-hidden="true" tabindex="-1"></a>*Diagram showing meaning of positive and negative angle values*</span>
<span id="cb10-316"><a href="#cb10-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-317"><a href="#cb10-317" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.2.8]*</span>
<span id="cb10-318"><a href="#cb10-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-319"><a href="#cb10-319" aria-hidden="true" tabindex="-1"></a>The real angle of the images was – to within around 2 degrees of accuracy – 17 degrees, so the estimated value is valid. The prototype determines whether&nbsp; the angle of the camera is acceptable or not. As before, a tolerance value is chosen- this time five degrees- and, clearly, 17 degrees lies outside this tolerance. Thus the code informs the user how far the camera has to be rotated in order for it to be correctly positioned, waits for the user to reposition it and take a new image, and loads the new image.</span>
<span id="cb10-320"><a href="#cb10-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-321"><a href="#cb10-321" aria-hidden="true" tabindex="-1"></a>With the new image, the process repeats again. With the test case, input image, and the mask of the image, are as follows:&nbsp;</span>
<span id="cb10-322"><a href="#cb10-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-323"><a href="#cb10-323" aria-hidden="true" tabindex="-1"></a>*(a)                    (b)*</span>
<span id="cb10-324"><a href="#cb10-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-325"><a href="#cb10-325" aria-hidden="true" tabindex="-1"></a>*The third input image (a), and its marker mask (b)*</span>
<span id="cb10-326"><a href="#cb10-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-327"><a href="#cb10-327" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.2.9]*</span>
<span id="cb10-328"><a href="#cb10-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-329"><a href="#cb10-329" aria-hidden="true" tabindex="-1"></a>This gives marker positions as follows:</span>
<span id="cb10-330"><a href="#cb10-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-331"><a href="#cb10-331" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-332"><a href="#cb10-332" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-333"><a href="#cb10-333" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-334"><a href="#cb10-334" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-335"><a href="#cb10-335" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-336"><a href="#cb10-336" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-337"><a href="#cb10-337" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-338"><a href="#cb10-338" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-339"><a href="#cb10-339" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-340"><a href="#cb10-340" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-341"><a href="#cb10-341" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-342"><a href="#cb10-342" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-343"><a href="#cb10-343" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-344"><a href="#cb10-344" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-345"><a href="#cb10-345" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-346"><a href="#cb10-346" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-347"><a href="#cb10-347" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-348"><a href="#cb10-348" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-349"><a href="#cb10-349" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-350"><a href="#cb10-350" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-351"><a href="#cb10-351" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-352"><a href="#cb10-352" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-353"><a href="#cb10-353" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-354"><a href="#cb10-354" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-355"><a href="#cb10-355" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-356"><a href="#cb10-356" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-357"><a href="#cb10-357" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-358"><a href="#cb10-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-359"><a href="#cb10-359" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Point <span class="pp">|</span> x <span class="pp">|</span> y <span class="pp">|</span></span>
<span id="cb10-360"><a href="#cb10-360" aria-hidden="true" tabindex="-1"></a><span class="pp">| ---</span> <span class="pp">| ---</span> <span class="pp">| ---</span> <span class="pp">|</span></span>
<span id="cb10-361"><a href="#cb10-361" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Top Left <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb10-362"><a href="#cb10-362" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Top Right <span class="pp">|</span> 189.7 <span class="pp">|</span> -0.8 <span class="pp">|</span></span>
<span id="cb10-363"><a href="#cb10-363" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Bottom Left <span class="pp">|</span> 0.4 <span class="pp">|</span> 123.4 <span class="pp">|</span></span>
<span id="cb10-364"><a href="#cb10-364" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Bottom Right <span class="pp">|</span> 191.8 <span class="pp">|</span> 123.2 <span class="pp">|</span></span>
<span id="cb10-365"><a href="#cb10-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-366"><a href="#cb10-366" aria-hidden="true" tabindex="-1"></a>*New relative positions of marker centres*</span>
<span id="cb10-367"><a href="#cb10-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-368"><a href="#cb10-368" aria-hidden="true" tabindex="-1"></a>*[Table. 4.2.4]*</span>
<span id="cb10-369"><a href="#cb10-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-370"><a href="#cb10-370" aria-hidden="true" tabindex="-1"></a>Which gives a ratio of 1.00, which equates to an angle of 1.09 degrees; acceptable for passing to the next stage.</span>
<span id="cb10-371"><a href="#cb10-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-372"><a href="#cb10-372" aria-hidden="true" tabindex="-1"></a>***Stage 2: Finding Object Disparity***</span>
<span id="cb10-373"><a href="#cb10-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-374"><a href="#cb10-374" aria-hidden="true" tabindex="-1"></a>***Introduction***</span>
<span id="cb10-375"><a href="#cb10-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-376"><a href="#cb10-376" aria-hidden="true" tabindex="-1"></a>Now the camera has been positioned correctly, the prototype needs to determine how far the object (the red rectangle) is displaced from its position in the archive image. In all current (non-archive) images, the object is 6.0mm further to the right, and 4.0mm lower, than it is in the archive image.</span>
<span id="cb10-377"><a href="#cb10-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-378"><a href="#cb10-378" aria-hidden="true" tabindex="-1"></a>In order to determine the disparity of the object, any disparity between the test and archive images as a whole – known as rigid body disparity – needs to be determined. Stage one of the process allows the *angle* of the camera to be corrected relative to the plane, but does not correct the *position* along the axes of the plane from which the camera views the bounded area.&nbsp;</span>
<span id="cb10-379"><a href="#cb10-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-380"><a href="#cb10-380" aria-hidden="true" tabindex="-1"></a>Once this rigid body disparity has been found, it can be compensated for when performing a digital image correlation (DIC), so that ‘like’ regions – regions of the images common to both archive and current – can be compared.</span>
<span id="cb10-381"><a href="#cb10-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-382"><a href="#cb10-382" aria-hidden="true" tabindex="-1"></a>An object disparity value found by performing a DIC on the common regions of the pair of images, in pixels, then needs to be converted to a value in millimetres, by using a scale found by comparing real-life boundary marker geometries with those located in pixels.</span>
<span id="cb10-383"><a href="#cb10-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-384"><a href="#cb10-384" aria-hidden="true" tabindex="-1"></a>Thus, stage two essentially involves three sub-stages, each of which will now be detailed for the test case in sequence.</span>
<span id="cb10-385"><a href="#cb10-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-386"><a href="#cb10-386" aria-hidden="true" tabindex="-1"></a>***Sub-stage 1: Rigid-body Disparity***</span>
<span id="cb10-387"><a href="#cb10-387" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-388"><a href="#cb10-388" aria-hidden="true" tabindex="-1"></a>Rigid body disparity, the disparity between two images due to a shift between the images as a whole (rather than displacement of a small-sub region of the image – i.e. the movable object), can be determined in a number of ways:&nbsp;</span>
<span id="cb10-389"><a href="#cb10-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-390"><a href="#cb10-390" aria-hidden="true" tabindex="-1"></a>If the images are of a flat surface with an amorphous (non-repeating) pattern on it – such as wood-chip wallpaper –, and where any movable objects within the image areas occupy only a small image area, and/or of a low intensity within the intensity plane used, then simply performing a DIC of both whole images should produce an output with the greatest intensity peak at the rigid-body displacement position.</span>
<span id="cb10-391"><a href="#cb10-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-392"><a href="#cb10-392" aria-hidden="true" tabindex="-1"></a>There are a number of problems with this approach: A DIC of the whole image will be affected by both rigid body and object disparity, and may produce a results whose peak is at a position that is a ‘compromise’ between the rigid-body displacement (which should have the greatest ‘energy’ in the image, as most of the features of the image match at this disparity position), and the object displacement. Thus it would produce the wrong value for rigid-body disparity.</span>
<span id="cb10-393"><a href="#cb10-393" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-394"><a href="#cb10-394" aria-hidden="true" tabindex="-1"></a>Also, most machine work surfaces do not have fixed amorphous patterns on them in a region of interest. Consider a work surface on a drilling machine: Originally, its work surface may be shiny and featureless; over time features on the surface may result in the form of scratches and general wear, but these features are likely to change over time - as more scratches are introduced -, and so cannot be used to determine rigid body disparity between two images taken – for instance – months apart.&nbsp;</span>
<span id="cb10-395"><a href="#cb10-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-396"><a href="#cb10-396" aria-hidden="true" tabindex="-1"></a>A better method, therefore, may be to use the boundary markers found in the previous stages. This should be more reliable, as they are strong, already identified features, which are not as subject to change in appearance over time than the region actually within the working area.</span>
<span id="cb10-397"><a href="#cb10-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-398"><a href="#cb10-398" aria-hidden="true" tabindex="-1"></a>Thus, in the test case, the rigid-body disparity is found by comparing the boundary marker masks of the current and archive image, rather than the images themselves.&nbsp;</span>
<span id="cb10-399"><a href="#cb10-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-400"><a href="#cb10-400" aria-hidden="true" tabindex="-1"></a>The image and mask for both the current image and the archive image are as follows:</span>
<span id="cb10-401"><a href="#cb10-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-402"><a href="#cb10-402" aria-hidden="true" tabindex="-1"></a>*(a)                    (b)*</span>
<span id="cb10-403"><a href="#cb10-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-404"><a href="#cb10-404" aria-hidden="true" tabindex="-1"></a>*The archive image (a) and the current image (b): Note that the lighting is significantly different for both images, but this does not affect the ability for the computer to identify the boundary markers*</span>
<span id="cb10-405"><a href="#cb10-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-406"><a href="#cb10-406" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.2.10]***</span>
<span id="cb10-407"><a href="#cb10-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-408"><a href="#cb10-408" aria-hidden="true" tabindex="-1"></a>*(a)                    (b)*</span>
<span id="cb10-409"><a href="#cb10-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-410"><a href="#cb10-410" aria-hidden="true" tabindex="-1"></a>*The archive mask (a) and the current mask (b): The differences in lighting are compensated for*</span>
<span id="cb10-411"><a href="#cb10-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-412"><a href="#cb10-412" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.2.11]*</span>
<span id="cb10-413"><a href="#cb10-413" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-414"><a href="#cb10-414" aria-hidden="true" tabindex="-1"></a>This produces the following normalised cross-correlation image:</span>
<span id="cb10-415"><a href="#cb10-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-416"><a href="#cb10-416" aria-hidden="true" tabindex="-1"></a>*Normalised cross-correlation of the two masks: Note the clarity of the main intensity peak*</span>
<span id="cb10-417"><a href="#cb10-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-418"><a href="#cb10-418" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.2.12]*</span>
<span id="cb10-419"><a href="#cb10-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-420"><a href="#cb10-420" aria-hidden="true" tabindex="-1"></a>The position of the peak is identified at x = -20 pixels, and y = 1 pixel.&nbsp;</span>
<span id="cb10-421"><a href="#cb10-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-422"><a href="#cb10-422" aria-hidden="true" tabindex="-1"></a>This *is* the ***rigid body disparity*** *in pixels*.</span>
<span id="cb10-423"><a href="#cb10-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-424"><a href="#cb10-424" aria-hidden="true" tabindex="-1"></a>***Sub-stage 2: Object Disparity***</span>
<span id="cb10-425"><a href="#cb10-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-426"><a href="#cb10-426" aria-hidden="true" tabindex="-1"></a>Having identified the rigid body disparity, one now needs to identify the displacement of the object *within the plane*, rather than in the images.</span>
<span id="cb10-427"><a href="#cb10-427" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-428"><a href="#cb10-428" aria-hidden="true" tabindex="-1"></a>The object is located (almost) exclusively in both images by using the technique given in section 2.3.3, giving the following pair of intensity planes:</span>
<span id="cb10-429"><a href="#cb10-429" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-430"><a href="#cb10-430" aria-hidden="true" tabindex="-1"></a>*(a)                    (b)***</span>
<span id="cb10-431"><a href="#cb10-431" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-432"><a href="#cb10-432" aria-hidden="true" tabindex="-1"></a>*Object colour intensity plane images from (a) the archive image and (b) the current image*</span>
<span id="cb10-433"><a href="#cb10-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-434"><a href="#cb10-434" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.2.13]*</span>
<span id="cb10-435"><a href="#cb10-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-436"><a href="#cb10-436" aria-hidden="true" tabindex="-1"></a>The displacement between the objects in these two images could be considered to the sum of the object disparity, and the rigid body disparity. One could simply determine this disparity, and subtract the rigid body disparity from it to obtain the object disparity; or one could use the rigid body information to form *rigid-body compensated* object images. These images show only the regions of the larger images common to both images:</span>
<span id="cb10-437"><a href="#cb10-437" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-438"><a href="#cb10-438" aria-hidden="true" tabindex="-1"></a>*(a)                    (b)***</span>
<span id="cb10-439"><a href="#cb10-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-440"><a href="#cb10-440" aria-hidden="true" tabindex="-1"></a>*Rigid-body compensated object intensity planes: These images now show only the regions of the original images common to both; rigid-body disparity has been removed&nbsp;*</span>
<span id="cb10-441"><a href="#cb10-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-442"><a href="#cb10-442" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.2.14]*</span>
<span id="cb10-443"><a href="#cb10-443" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-444"><a href="#cb10-444" aria-hidden="true" tabindex="-1"></a>These images are 20 pixels (the x-axis RB disparity) smaller in width, and 1 pixel (the y-axis RB disparity) smaller in height. As they are smaller, the region containing the object represents a larger proportion of the total image area, and thus has a stronger presence within the image, and produces a slightly more pronounced peak when DIC is used on it:</span>
<span id="cb10-445"><a href="#cb10-445" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-446"><a href="#cb10-446" aria-hidden="true" tabindex="-1"></a>*NCC of the RB compensated object images&nbsp;*</span>
<span id="cb10-447"><a href="#cb10-447" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-448"><a href="#cb10-448" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.2.15]*</span>
<span id="cb10-449"><a href="#cb10-449" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-450"><a href="#cb10-450" aria-hidden="true" tabindex="-1"></a>The position of the peak on this NCC graph (Fig. 4.2.15) is x = 15 pixels, and y = 10 pixels.</span>
<span id="cb10-451"><a href="#cb10-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-452"><a href="#cb10-452" aria-hidden="true" tabindex="-1"></a>This is the recorded value of the object disparity.</span>
<span id="cb10-453"><a href="#cb10-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-454"><a href="#cb10-454" aria-hidden="true" tabindex="-1"></a>One can consider how accurate these values seem by comparing them with the actual object displacement: 6.0mm to the right, and 4.0mm downward. Due to the way Matlab stores images, the origin is taken as the top left corner, thus displacements to the right, and downward, are both positive displacements. Both the x and y object displacement values are positive, which means the recorded object displacement is in the correct direction.&nbsp;</span>
<span id="cb10-455"><a href="#cb10-455" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-456"><a href="#cb10-456" aria-hidden="true" tabindex="-1"></a>The ratio between x displacement and y displacement in both cases (actual in mm, and recorded in pixels) is 3/2 (15pixels/10pixels = 6mm/4mm = 3/2), again suggesting that the displacement value found is accurate.</span>
<span id="cb10-457"><a href="#cb10-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-458"><a href="#cb10-458" aria-hidden="true" tabindex="-1"></a>***Sub-stage 3: Real-life Disparity***</span>
<span id="cb10-459"><a href="#cb10-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-460"><a href="#cb10-460" aria-hidden="true" tabindex="-1"></a>The final stage involves converting the pixel disparities into millimetre disparities, by finding the ratio between pixels and millimetres.</span>
<span id="cb10-461"><a href="#cb10-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-462"><a href="#cb10-462" aria-hidden="true" tabindex="-1"></a>The locations of the marker centres on the current image are as follows:</span>
<span id="cb10-463"><a href="#cb10-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-464"><a href="#cb10-464" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-465"><a href="#cb10-465" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-466"><a href="#cb10-466" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-467"><a href="#cb10-467" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-468"><a href="#cb10-468" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-469"><a href="#cb10-469" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-470"><a href="#cb10-470" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-471"><a href="#cb10-471" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-472"><a href="#cb10-472" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-473"><a href="#cb10-473" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-474"><a href="#cb10-474" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-475"><a href="#cb10-475" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-476"><a href="#cb10-476" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-477"><a href="#cb10-477" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-478"><a href="#cb10-478" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-479"><a href="#cb10-479" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-480"><a href="#cb10-480" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-481"><a href="#cb10-481" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-482"><a href="#cb10-482" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-483"><a href="#cb10-483" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-484"><a href="#cb10-484" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-485"><a href="#cb10-485" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-486"><a href="#cb10-486" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-487"><a href="#cb10-487" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-488"><a href="#cb10-488" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-489"><a href="#cb10-489" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-490"><a href="#cb10-490" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-491"><a href="#cb10-491" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-492"><a href="#cb10-492" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Point <span class="pp">|</span> x <span class="pp">|</span> y <span class="pp">|</span></span>
<span id="cb10-493"><a href="#cb10-493" aria-hidden="true" tabindex="-1"></a><span class="pp">| ---</span> <span class="pp">| ---</span> <span class="pp">| ---</span> <span class="pp">|</span></span>
<span id="cb10-494"><a href="#cb10-494" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Top Left <span class="pp">|</span> 68.1 <span class="pp">|</span> 54.5 <span class="pp">|</span></span>
<span id="cb10-495"><a href="#cb10-495" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Top Right <span class="pp">|</span> 257.8 <span class="pp">|</span> 53.7 <span class="pp">|</span></span>
<span id="cb10-496"><a href="#cb10-496" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Bottom Left <span class="pp">|</span> 68.5 <span class="pp">|</span> 177.9 <span class="pp">|</span></span>
<span id="cb10-497"><a href="#cb10-497" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Bottom Right <span class="pp">|</span> 259.9 <span class="pp">|</span> 177.7 <span class="pp">|</span></span>
<span id="cb10-498"><a href="#cb10-498" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-499"><a href="#cb10-499" aria-hidden="true" tabindex="-1"></a>*Positions of marker centres – in pixels*</span>
<span id="cb10-500"><a href="#cb10-500" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-501"><a href="#cb10-501" aria-hidden="true" tabindex="-1"></a>*[Table. 4.2.5]***</span>
<span id="cb10-502"><a href="#cb10-502" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-503"><a href="#cb10-503" aria-hidden="true" tabindex="-1"></a>The position of the two horizontal edges – Top right (x) less top left (x), and bottom right (x) less bottom left (x) – are not exactly the same, so a mean is used, to provide an average horizontal edge length in pixels. The same is done with the two vertical edges, giving a horizontal edge value of 190.5 pixels, and a vertical edge value of 123.7 pixels.</span>
<span id="cb10-504"><a href="#cb10-504" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-505"><a href="#cb10-505" aria-hidden="true" tabindex="-1"></a>From the data provided at the start on real geometry, the real vertical edge distance is 70.0mm, and the vertical edge distance is 50.0mm. Dividing real edge distance by pixel edge distances gives a vertical ratio of 0.40 mm per pixel, and a horizontal ratio of 0.37 mm per pixel. These figures could be thought of as representing the system *resolution*, without resorting to sub-pixel algorithms.</span>
<span id="cb10-506"><a href="#cb10-506" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-507"><a href="#cb10-507" aria-hidden="true" tabindex="-1"></a>Multiplying the pixel disparities by these ratios gives real-life disparity estimates of 5.5mm (actual: 6.0mm) horizontally, and 4.0mm (actual: 4.0mm) vertically. This gives an overall magnitude of displacement of 6.8mm (actual 7.2mm). Thus the disparity values are accurate to within half a millimetre of the true value, in both the horizontal and vertical axes.</span>
<span id="cb10-508"><a href="#cb10-508" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-509"><a href="#cb10-509" aria-hidden="true" tabindex="-1"></a>The bounded object plane area was 70.0mm x 50.0mm, or 3500.0mm^2^; the object displacement figure found was accurate to ±0.5mm^2^ (The square root of 0.5^2^ + 0.0^2^). This gives a calculated accuracy level to within 0.5 / 3500, or 0.14 per ***mil****.* Using the 0.40 and 0.37 mm / pixel resolution figures calculated earlier gives a displacement determination accuracy of ±0.54mm^2^, the same value to 1 significant figure.&nbsp;</span>
<span id="cb10-510"><a href="#cb10-510" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-511"><a href="#cb10-511" aria-hidden="true" tabindex="-1"></a>***Other Examples***</span>
<span id="cb10-512"><a href="#cb10-512" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-513"><a href="#cb10-513" aria-hidden="true" tabindex="-1"></a>***Introduction***</span>
<span id="cb10-514"><a href="#cb10-514" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-515"><a href="#cb10-515" aria-hidden="true" tabindex="-1"></a>Though the example given in the previous section shows how the processes work, it does not show how the processes operate in other conditions.</span>
<span id="cb10-516"><a href="#cb10-516" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-517"><a href="#cb10-517" aria-hidden="true" tabindex="-1"></a>***Effect Of Non-critical Objects On Identification Of Critical Objects***</span>
<span id="cb10-518"><a href="#cb10-518" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-519"><a href="#cb10-519" aria-hidden="true" tabindex="-1"></a>In the prototype, two types of object need to be identified: those that mark the boundaries of the area of interest, and the movable object of interest. These are identified by colour. Below, three examples are given where camera position, and movable object of interest are fixed, but other objects – of a non-specified colour – differ in position:</span>
<span id="cb10-520"><a href="#cb10-520" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-521"><a href="#cb10-521" aria-hidden="true" tabindex="-1"></a>*Test Image 1       Marker Mask         Object Mask*</span>
<span id="cb10-522"><a href="#cb10-522" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-523"><a href="#cb10-523" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.3.1]***</span>
<span id="cb10-524"><a href="#cb10-524" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-525"><a href="#cb10-525" aria-hidden="true" tabindex="-1"></a>*Test Image 2       Marker Mask         Object Mask*</span>
<span id="cb10-526"><a href="#cb10-526" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-527"><a href="#cb10-527" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.3.2]***</span>
<span id="cb10-528"><a href="#cb10-528" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-529"><a href="#cb10-529" aria-hidden="true" tabindex="-1"></a>*Test Image 3       Marker Mask         Object Mask*</span>
<span id="cb10-530"><a href="#cb10-530" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-531"><a href="#cb10-531" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.3.3]***</span>
<span id="cb10-532"><a href="#cb10-532" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-533"><a href="#cb10-533" aria-hidden="true" tabindex="-1"></a>In two of the three cases, the system is able to identify both the markers and the movable object exclusively, without any difficulty. In the third image (Fig 4.3.3), part of a shadow formed by one of the non-critical objects is of a colour and intensity (black), and of a significant enough size, to be wrongly identified as part of a marker. This is a problem specific to greyscale (rather than colour) markers, and again highlights why colour marker colours are often used (Note that the object mask, of a vivid red colour, was successfully and exclusively identified in all three cases). Even this erroneously included portion of the feature could be successfully identified as erroneous by the computer and removed by, for instance, further erosion filtering, or simply (as, in the prototype case, there are just four markers) retaining only the largest object in each quarter of the mask.&nbsp;</span>
<span id="cb10-534"><a href="#cb10-534" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-535"><a href="#cb10-535" aria-hidden="true" tabindex="-1"></a>Where erroneously identified objects exist that are of similar or greater size to the correctly identified mask features, a more complicated system - that, for example, determines which of the feature objects identified in the mask is *most likely* to be the real one based on the known marker geometry – would have to be used.</span>
<span id="cb10-536"><a href="#cb10-536" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-537"><a href="#cb10-537" aria-hidden="true" tabindex="-1"></a>***Effects Of Lighting***</span>
<span id="cb10-538"><a href="#cb10-538" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-539"><a href="#cb10-539" aria-hidden="true" tabindex="-1"></a>So far, all examples shown have been ones where ambient lighting has been of a normal level; the image was neither dark nor light, and the camera neither over exposed or underexposed. The following images show some of the effects of different types of ambient lighting conditions, including many which are sub-optimal:</span>
<span id="cb10-540"><a href="#cb10-540" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-541"><a href="#cb10-541" aria-hidden="true" tabindex="-1"></a>*Test Image 1       Marker Mask         Object Mask*</span>
<span id="cb10-542"><a href="#cb10-542" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-543"><a href="#cb10-543" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.3.4]*</span>
<span id="cb10-544"><a href="#cb10-544" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-545"><a href="#cb10-545" aria-hidden="true" tabindex="-1"></a>*Test Image 2       Marker Mask         Object Mask*</span>
<span id="cb10-546"><a href="#cb10-546" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-547"><a href="#cb10-547" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.3.5]***</span>
<span id="cb10-548"><a href="#cb10-548" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-549"><a href="#cb10-549" aria-hidden="true" tabindex="-1"></a>*Test Image 3       Marker Mask         Object Mask*</span>
<span id="cb10-550"><a href="#cb10-550" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-551"><a href="#cb10-551" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.3.6]***</span>
<span id="cb10-552"><a href="#cb10-552" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-553"><a href="#cb10-553" aria-hidden="true" tabindex="-1"></a>*Test Image 4       Marker Mask         Object Mask*</span>
<span id="cb10-554"><a href="#cb10-554" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-555"><a href="#cb10-555" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.3.7]***</span>
<span id="cb10-556"><a href="#cb10-556" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-557"><a href="#cb10-557" aria-hidden="true" tabindex="-1"></a>*Test Image 5       Marker Mask         Object Mask*</span>
<span id="cb10-558"><a href="#cb10-558" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-559"><a href="#cb10-559" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.3.8]***</span>
<span id="cb10-560"><a href="#cb10-560" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-561"><a href="#cb10-561" aria-hidden="true" tabindex="-1"></a>*Test Image 6       Marker Mask         Object Mask*</span>
<span id="cb10-562"><a href="#cb10-562" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-563"><a href="#cb10-563" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.3.9]***</span>
<span id="cb10-564"><a href="#cb10-564" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-565"><a href="#cb10-565" aria-hidden="true" tabindex="-1"></a>A table summarising image descriptions and results is as follows:</span>
<span id="cb10-566"><a href="#cb10-566" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-567"><a href="#cb10-567" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-568"><a href="#cb10-568" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-569"><a href="#cb10-569" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-570"><a href="#cb10-570" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-571"><a href="#cb10-571" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-572"><a href="#cb10-572" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-573"><a href="#cb10-573" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-574"><a href="#cb10-574" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-575"><a href="#cb10-575" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-576"><a href="#cb10-576" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-577"><a href="#cb10-577" aria-hidden="true" tabindex="-1"></a><span class="in">      **</span></span>
<span id="cb10-578"><a href="#cb10-578" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-579"><a href="#cb10-579" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-580"><a href="#cb10-580" aria-hidden="true" tabindex="-1"></a><span class="in">      **</span></span>
<span id="cb10-581"><a href="#cb10-581" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-582"><a href="#cb10-582" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-583"><a href="#cb10-583" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-584"><a href="#cb10-584" aria-hidden="true" tabindex="-1"></a><span class="in">      **</span></span>
<span id="cb10-585"><a href="#cb10-585" aria-hidden="true" tabindex="-1"></a><span class="in">      ********</span></span>
<span id="cb10-586"><a href="#cb10-586" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-587"><a href="#cb10-587" aria-hidden="true" tabindex="-1"></a><span class="in">      **</span></span>
<span id="cb10-588"><a href="#cb10-588" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-589"><a href="#cb10-589" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-590"><a href="#cb10-590" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-591"><a href="#cb10-591" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-592"><a href="#cb10-592" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-593"><a href="#cb10-593" aria-hidden="true" tabindex="-1"></a><span class="in">      **********</span></span>
<span id="cb10-594"><a href="#cb10-594" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-595"><a href="#cb10-595" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-596"><a href="#cb10-596" aria-hidden="true" tabindex="-1"></a><span class="in">      **</span></span>
<span id="cb10-597"><a href="#cb10-597" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-598"><a href="#cb10-598" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-599"><a href="#cb10-599" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-600"><a href="#cb10-600" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-601"><a href="#cb10-601" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-602"><a href="#cb10-602" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-603"><a href="#cb10-603" aria-hidden="true" tabindex="-1"></a><span class="in">      **********</span></span>
<span id="cb10-604"><a href="#cb10-604" aria-hidden="true" tabindex="-1"></a><span class="in">      **</span></span>
<span id="cb10-605"><a href="#cb10-605" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-606"><a href="#cb10-606" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-607"><a href="#cb10-607" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-608"><a href="#cb10-608" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-609"><a href="#cb10-609" aria-hidden="true" tabindex="-1"></a><span class="in">      ********</span></span>
<span id="cb10-610"><a href="#cb10-610" aria-hidden="true" tabindex="-1"></a><span class="in">      ********</span></span>
<span id="cb10-611"><a href="#cb10-611" aria-hidden="true" tabindex="-1"></a><span class="in">      **</span></span>
<span id="cb10-612"><a href="#cb10-612" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-613"><a href="#cb10-613" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-614"><a href="#cb10-614" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-615"><a href="#cb10-615" aria-hidden="true" tabindex="-1"></a><span class="in">      **</span></span>
<span id="cb10-616"><a href="#cb10-616" aria-hidden="true" tabindex="-1"></a><span class="in">      ********</span></span>
<span id="cb10-617"><a href="#cb10-617" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-618"><a href="#cb10-618" aria-hidden="true" tabindex="-1"></a><span class="in">      **</span></span>
<span id="cb10-619"><a href="#cb10-619" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-620"><a href="#cb10-620" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-621"><a href="#cb10-621" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-622"><a href="#cb10-622" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-623"><a href="#cb10-623" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Image Number <span class="pp">|</span> Description <span class="pp">|</span> Marker Identification <span class="pp">|</span> Object Identification <span class="pp">|</span> Comment <span class="pp">|</span></span>
<span id="cb10-624"><a href="#cb10-624" aria-hidden="true" tabindex="-1"></a><span class="pp">| ---</span> <span class="pp">| ---</span> <span class="pp">| ---</span> <span class="pp">| ---</span> <span class="pp">| ---</span> <span class="pp">|</span></span>
<span id="cb10-625"><a href="#cb10-625" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> Normal, constant ambient lighting. <span class="pp">|</span> OK <span class="pp">|</span> OK <span class="pp">|</span> Control Case <span class="pp">|</span></span>
<span id="cb10-626"><a href="#cb10-626" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> Dark /underexposed. Even/ constant lighting. <span class="pp">|</span> Not OK – Three erroneous features. Not connected to correct features <span class="pp">|</span> OK <span class="pp">|</span>  <span class="pp">|</span></span>
<span id="cb10-627"><a href="#cb10-627" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> Dark/ underexposed.</span>
<span id="cb10-628"><a href="#cb10-628" aria-hidden="true" tabindex="-1"></a>        Uneven lighting. | Not OK – four erroneous features. One connected to marker object | OK |  |</span>
<span id="cb10-629"><a href="#cb10-629" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 4 <span class="pp">|</span> Overexposed/ bright.</span>
<span id="cb10-630"><a href="#cb10-630" aria-hidden="true" tabindex="-1"></a>        Even lighting (directly from behind) | OK | Not OK –&nbsp;</span>
<span id="cb10-631"><a href="#cb10-631" aria-hidden="true" tabindex="-1"></a>        Not identified | Marker mask is sharp |</span>
<span id="cb10-632"><a href="#cb10-632" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 5 <span class="pp">|</span> Overexposed/ bright.</span>
<span id="cb10-633"><a href="#cb10-633" aria-hidden="true" tabindex="-1"></a>        Uneven lighting (from bottom left hand side) | Not OK – One feature erroneously identified | Not OK – Object correctly identified, but brightest corner of image also erroneously identified as image | Objects connected to image corner or edge can be identified as erroneous and removed |</span>
<span id="cb10-634"><a href="#cb10-634" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 6 <span class="pp">|</span> Uneven lighting, partially bright, partially dark <span class="pp">|</span> Not OK – One feature erroneously identified <span class="pp">|</span> OK <span class="pp">|</span>  <span class="pp">|</span></span>
<span id="cb10-635"><a href="#cb10-635" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-636"><a href="#cb10-636" aria-hidden="true" tabindex="-1"></a>*Table of lighting effects on object identification*</span>
<span id="cb10-637"><a href="#cb10-637" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-638"><a href="#cb10-638" aria-hidden="true" tabindex="-1"></a>*[Table. 4.3.1]***</span>
<span id="cb10-639"><a href="#cb10-639" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-640"><a href="#cb10-640" aria-hidden="true" tabindex="-1"></a>As stated previously, using a greyscale marker represents a worst-case scenario regarding ease of identification. This shows in these results, where the shadow formed by one particular non-critical object, near the top right of the bounded area, is erroneously identified in almost every marker mark of the image with sub-optimal lighting. In images 2 and 3, even more objects are included erroneously. In no cases, however, are the correct objects not *identified,* and only in image 3 does an erroneous feature ‘bleed’ into a marker (making removing erroneous features exclusively more difficult).&nbsp;</span>
<span id="cb10-641"><a href="#cb10-641" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-642"><a href="#cb10-642" aria-hidden="true" tabindex="-1"></a>In comparison, the red object was correctly and exclusively identified in almost all cases. When the camera was greatly overexposed (Image 4), the program was unable to differentiate between the object and its background, and thus it was not identified. In the other case (Image 5), part of the edge of the image was overexposed, and incorrectly identified. However, as the object is known to not be on the edge of the image, and the erroneous feature was not connected to it, the erroneous feature could identified as such and removed quite easily.</span>
<span id="cb10-643"><a href="#cb10-643" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-644"><a href="#cb10-644" aria-hidden="true" tabindex="-1"></a>The results of image 4 are important, as, in this case, the markers were easily identified. This type of image could be created by either increasing the contrast of the camera, or by switching on a portable light source behind the camera. This would have the effect of removing the effect of uneven lighting on creating erroneous feature identification (such as in image 5), and more easily than attempting to *block* light. Afterwards, the light source could be de-activated to allow the red object to be identified.</span>
<span id="cb10-645"><a href="#cb10-645" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-646"><a href="#cb10-646" aria-hidden="true" tabindex="-1"></a>In a more general case, a strong light source that makes features of a certain colour more prominent could be used to make identifying that particular feature easier.</span>
<span id="cb10-647"><a href="#cb10-647" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-648"><a href="#cb10-648" aria-hidden="true" tabindex="-1"></a>***Effects Of Camera Distance***</span>
<span id="cb10-649"><a href="#cb10-649" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-650"><a href="#cb10-650" aria-hidden="true" tabindex="-1"></a>So far, all tests have been conducted at a single distance (154mm). The following table shows the effect changing the distance has on the calculated ratio of right side vertical distance between markers to left side distance- used to calculate the horizontal plane angle of the camera to the object plane – at 30 degrees to the left of the normal angle.&nbsp;</span>
<span id="cb10-651"><a href="#cb10-651" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-652"><a href="#cb10-652" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-653"><a href="#cb10-653" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-654"><a href="#cb10-654" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-655"><a href="#cb10-655" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-656"><a href="#cb10-656" aria-hidden="true" tabindex="-1"></a><span class="in">      ****</span></span>
<span id="cb10-657"><a href="#cb10-657" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-658"><a href="#cb10-658" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-659"><a href="#cb10-659" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-660"><a href="#cb10-660" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-661"><a href="#cb10-661" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-662"><a href="#cb10-662" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-663"><a href="#cb10-663" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-664"><a href="#cb10-664" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-665"><a href="#cb10-665" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-666"><a href="#cb10-666" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-667"><a href="#cb10-667" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-668"><a href="#cb10-668" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-669"><a href="#cb10-669" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-670"><a href="#cb10-670" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-671"><a href="#cb10-671" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-672"><a href="#cb10-672" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-673"><a href="#cb10-673" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-674"><a href="#cb10-674" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-675"><a href="#cb10-675" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-676"><a href="#cb10-676" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-677"><a href="#cb10-677" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-678"><a href="#cb10-678" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-679"><a href="#cb10-679" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-680"><a href="#cb10-680" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-681"><a href="#cb10-681" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-682"><a href="#cb10-682" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-683"><a href="#cb10-683" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-684"><a href="#cb10-684" aria-hidden="true" tabindex="-1"></a><span class="in">      ******</span></span>
<span id="cb10-685"><a href="#cb10-685" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-686"><a href="#cb10-686" aria-hidden="true" tabindex="-1"></a><span class="in">      </span></span>
<span id="cb10-687"><a href="#cb10-687" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb10-688"><a href="#cb10-688" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-689"><a href="#cb10-689" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-690"><a href="#cb10-690" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Distance (mm) <span class="pp">|</span> Ratio (RHS / LHS) <span class="pp">|</span> Relative Ratio <span class="pp">|</span></span>
<span id="cb10-691"><a href="#cb10-691" aria-hidden="true" tabindex="-1"></a><span class="pp">| ---</span> <span class="pp">| ---</span> <span class="pp">| ---</span> <span class="pp">|</span></span>
<span id="cb10-692"><a href="#cb10-692" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 154 <span class="pp">|</span> 0.86 <span class="pp">|</span> 1.00 <span class="pp">|</span></span>
<span id="cb10-693"><a href="#cb10-693" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 174 <span class="pp">|</span> 0.87 <span class="pp">|</span> 1.02 <span class="pp">|</span></span>
<span id="cb10-694"><a href="#cb10-694" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 194 <span class="pp">|</span> 0.88 <span class="pp">|</span> 1.03 <span class="pp">|</span></span>
<span id="cb10-695"><a href="#cb10-695" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 214 <span class="pp">|</span> 0.89 <span class="pp">|</span> 1.03 <span class="pp">|</span></span>
<span id="cb10-696"><a href="#cb10-696" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 234 <span class="pp">|</span> 0.89 <span class="pp">|</span> 1.04 <span class="pp">|</span></span>
<span id="cb10-697"><a href="#cb10-697" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 254 <span class="pp">|</span> 0.90 <span class="pp">|</span> 1.05 <span class="pp">|</span></span>
<span id="cb10-698"><a href="#cb10-698" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-699"><a href="#cb10-699" aria-hidden="true" tabindex="-1"></a>*Table of effect of distance on calculated ratio*</span>
<span id="cb10-700"><a href="#cb10-700" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-701"><a href="#cb10-701" aria-hidden="true" tabindex="-1"></a>*[Table. 4.3.2]*</span>
<span id="cb10-702"><a href="#cb10-702" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-703"><a href="#cb10-703" aria-hidden="true" tabindex="-1"></a>*Masks used to calculate ratios at same angle and different distances*</span>
<span id="cb10-704"><a href="#cb10-704" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-705"><a href="#cb10-705" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.3.10]***</span>
<span id="cb10-706"><a href="#cb10-706" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-707"><a href="#cb10-707" aria-hidden="true" tabindex="-1"></a>As one can see, as the distance increases, the ratio tends towards 1. This makes sense due to the effects a limited resolution has on the way an object is interpreted at different distances. As the object gets further away, more information about it is lost, and less can be interpreted about it. Even looking at the masks of the images, they start to appear more rectangular when smaller, and this effect is resulting in the increasingly inaccurate ratio results.</span>
<span id="cb10-708"><a href="#cb10-708" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-709"><a href="#cb10-709" aria-hidden="true" tabindex="-1"></a>It would be possible to use the actual number of pixels between markers, and the size of markers in the images, to estimate the distance from the camera to the plane, and thus the accuracy of other figures such as estimated angle.&nbsp;</span>
<span id="cb10-710"><a href="#cb10-710" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-711"><a href="#cb10-711" aria-hidden="true" tabindex="-1"></a>In DIC, is important that the two images to be correlated are at the same distance (as well as angle). Thus, a final system would need to be able to determine and inform the user of its distance from the plane, as well as angle to it. &nbsp;</span>
<span id="cb10-712"><a href="#cb10-712" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-713"><a href="#cb10-713" aria-hidden="true" tabindex="-1"></a>***4.4  Calibration***</span>
<span id="cb10-714"><a href="#cb10-714" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-715"><a href="#cb10-715" aria-hidden="true" tabindex="-1"></a>For stage 1b, it was required that the prototype device be able to determine an angle from a ratio. This required prior calibration: 10 sets of 17 images, at a set distance and horizontal plane angles varying incrementally from –40 degrees to 40 degrees in 5 degree steps, were taken, and the ratio between left vertical edge and right vertical edge (as in the previous example) were found.&nbsp;</span>
<span id="cb10-716"><a href="#cb10-716" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-717"><a href="#cb10-717" aria-hidden="true" tabindex="-1"></a>The average value at each of these angles, from all 10 cases, was found, giving the following results when plotted against angle:</span>
<span id="cb10-718"><a href="#cb10-718" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-719"><a href="#cb10-719" aria-hidden="true" tabindex="-1"></a>*Graph of ratio to angle*</span>
<span id="cb10-720"><a href="#cb10-720" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-721"><a href="#cb10-721" aria-hidden="true" tabindex="-1"></a>*[Fig. 4.4.1]*</span>
<span id="cb10-722"><a href="#cb10-722" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-723"><a href="#cb10-723" aria-hidden="true" tabindex="-1"></a>A third degree polynomial approximation, equating ratio to angle, was found, and the coefficients generated stored. The Matlab functions *polyfit *and *polytool* were used, and the red lines on the above graph show the *polytool* estimated error level of the polynomial fit to the real values. These are loaded into the stage 1b code, and used to calculate the horizontal plane angle.</span>
<span id="cb10-724"><a href="#cb10-724" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-725"><a href="#cb10-725" aria-hidden="true" tabindex="-1"></a>The coefficients, in descending order, are: **272.6; &nbsp; -914.3;  1,152.0; &nbsp; -509.9**</span>
<span id="cb10-726"><a href="#cb10-726" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-727"><a href="#cb10-727" aria-hidden="true" tabindex="-1"></a>i.e. <span class="co">[</span><span class="ot">*equation*</span><span class="co">]</span>{.eqn-ref} *[Eqn. 4.4.1]*</span>
<span id="cb10-728"><a href="#cb10-728" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-729"><a href="#cb10-729" aria-hidden="true" tabindex="-1"></a>As an example, the ratio value 1.08 (r = 1.08) leads to an angle (θ) estimate of 11.2 degrees. Using r = 1.04 yields θ = 5.9 degrees.</span>
<span id="cb10-730"><a href="#cb10-730" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-731"><a href="#cb10-731" aria-hidden="true" tabindex="-1"></a>*Negative angle*</span>
<span id="cb10-732"><a href="#cb10-732" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-733"><a href="#cb10-733" aria-hidden="true" tabindex="-1"></a>*Positive angle*</span>
<span id="cb10-734"><a href="#cb10-734" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-735"><a href="#cb10-735" aria-hidden="true" tabindex="-1"></a>**Object plane**</span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Jon Minton, 2003-2009 (archived 2026)</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions"><ul><li><a href="https://github.com/JonMinton/academic-works/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>