---
title: "Chaos and Complexity"
---

Chaos and Complexity
The terms ‘chaotic’, ‘complex’ and ‘complicated’, often seem to be used interchangeably, and so I believe it would be worthwhile for me to explain how I shall be using the terms, and what the differences between them are. I’ll try to offer, where available, citations and ‘authoritative’ arguments in favour of the definitions I’m using, but where I cannot one should just try to accept that sticking to any one consistent meaning for a term is generally better than not. Words are, after all, only meaningful through common social convention.

Chaotic: A phenomena is chaotic where some endogenous components of the system which characterise it exhibit positive feedback and apparent randomness. From a physicalist perspective, it might be considered that, in principle, all phenomena are perfectly predictable, as all comprise entirely of deterministic causal relationships. However, due to practical limits on the amount of information which can be collected and fed into a model designed to predict the phenomena, the most practicable model one could employ would be stochastic rather than deterministic.
A stochastic model might be considered a general framework which could encompass both completely random and completely non-random (deterministic) phenomena, employing such a model in either extreme case is only of conceptual rather than practical importance. A stochastic model includes at least one probabilistic function.
A probabilistic function differs from a deterministic function in that, unlike with a deterministic function, performing the same operation on a deterministic function may yield a different result. Understanding what this means could be helped with the following thought experiment:

Imagine a black box with two buttons and two lights. The buttons are labelled “Left” and “Right”, and the lights are labelled “Red” and “Blue” (for the simple reason that one of the buttons is on the left, and the other on the right; and that one of the lights produces red light, and the other produces blue light. The actual labels don’t matter. They merely help people to identify the different parts – the lights and the buttons – more easily.)
If one presses the button on the left (called “Left”), the red light turns on. When the button in the right (“Right”) is pressed, the blue light turns on. When neither of the buttons are pressed, neither of the lights are on. When both of the buttons are pressed, both of the lights are on.
In this case, each of the things one could do to the inputs leads to a particular thing happening to the lights. The black box is said to ‘map’ each of the possible combinations of button-pressing to a particular combination of light-illuminating.
The black box is said to*function*as a system which converts ‘inputs’ (the buttons) to ‘outputs’ (the lights). It is said to be deterministic because the same combination of inputs*always*leads to the same combination of outputs.

Consider another black box, which looks exactly the same as the one just described. This time, however, a particular input does not always lead to a particular output. “Left” does not always cause ‘Red”, and “Right” does not always cause “Blue”. Instead, a particular input leads may lead to a range of possible outputs: Pressing Left on one particular occasion leads to Red, another time it leads to Blue, another time it may lead to both Red and Blue at the same time, and another time it leads to neither Red nor Blue. This black box, unlike the previous one, is not deterministic.
Understanding this second black box requires doing the following: choose a particular input (Red or Blue individually, or both Red and Blue at the same time), and press it, observing what output this leads to. Then do this again, and again, and again… Continue doings this – pressing a particular input and observing the output – all the while recording what outputs one gets from the input, a large (but known) number of times.
Now, with the data one has just gathered from performing this simple experiment on the box, draw a histogram – a visual tally – of the number of times the particular input has led to each of the possible outputs. This histogram has a particular shape to it. This shape can be used to form a formal description of how the given input relates to the range of possible outputs. The formal description of how the given input relates to the range of outputs is known as a*probability function*, and possesses some conceptual subtlety which is important to understand: It is a way of mapping the given input to the range of outputs, rather than just a single output.
By performing this kind of experiment for each of the input combinations, a probability function can be constructed for each input combination, which defines how that particular input combination relates to any and all of the output combinations. As long as one assumes that nothing inside the black box has changed over the course of the experiments performed, and that the future will be like the past (i.e. that one is not wrong to use inductive reasoning), then one can use the probability functions one has created to try to predict what the outcome of a particular input combination will be. The prediction makes no intuitive sense for a single ‘trial’ of the system (i.e. a single ‘press’ of a particular combination of buttons), but does make some sense when talking about a collection of ‘trials’. The type of prediction one might make from the probability function might be along the lines of: “If I were to press the red button five times, I would expect to see the red light alone turn on three times, the blue light to turn one time, and both lights to turn on one time. I don’t know, however, the in which these output events will occur, however”. (If one then pressed the button five times, one might or might not see the tally one has not predicted. If, however, one performs multiple five-trial ‘trials’ (i.e. one performs a trial of trials), and finds an average of the number of trials [….]

This subsectioned has segued into a strange, brave and foolish attempt to describe the concepts behind functions and probability!.
I'm bored! I think I've demonstrated why mathematical formulae aren't just difficult to understand on purpose: they are ways of formally describing things which are difficult to describe verbally, as I have been trying to do just here!
