---
title: "Results"
---

4
  
  
  
  
  
  
  
  

** Results**

***4.1	Section Introduction***

This section provides results attained through the use and creation of the prototype system. It is split into three sub-sections: 

Results of all processes to a single test example.

Results of various processes to other example inputs.

Results required for machine calibration and testing system stability.

***Results Of System Using Single Test Case***

***Introduction***

Here, the stages of the prototype system listed in section 3 are demonstrated using a single test case.

In the test case, the bounded area was a rectangle 70mm wide and 50 mm high. This was marked out using four black square blocks 10 mm wide. Black was used as the marker colour as it is a poor choice of marker colour (due to the reasons given in section 2.3.2), and so demonstrating that the system works with this colour scheme suggest that it should also work with others (where the affect of bright lights and shadows can be more easily mitigated).

The object is represented by a small movable red rectangle 8mm wide and 6 mm high. Am image of this object within the bounded area, at the ‘correct’ position, is taken, and loaded, as an archived image, into the system at the start of the program sequence:

*Archive image of marker object (red rectangle) in correct position*

*[Fig. 4.2.1]*

Note that, within the bounded area, other objects, of a different colour, also exist. To work, the prototype system should not be affected by the position of these other objects. The background is graph paper, which, as a repeating pattern, creates ‘noise’ when a DIC approach is used (due to localised areas of image correlation). Both of these factors make the test case good for demonstrating the rigorousness of the system.

The geometry of the markers is also entered into the system at the start. The position of the four markers, from each other and in millimetres, is loaded into the system as the following 4 x 2 element array:

  
    
      
      
    
    
      
      
    
    
      
      
    
    
      
      
    
  

| 0 | 0 |
| --- | --- |
| 70 | 0 |
| 0 | 50 |
| 70 | 50 |

*Marker position matrix used*

*[Table. 4.2.1]*

Where the first column gives the horizontal distance from the origin, and the second gives the vertical distance from the origin.

Also given are information on the colour combination to use to find both the object marker (red), and the boundary markers (black). In the case of the boundary marker, this would be an instruction to convert the colour image into a greyscale image (by combining the pixel average of the three colour intensity plane) and then inverting, so dark areas become areas of high intensity. In the case of the red object marker, the procedure shown in section 2.3.3 is used. 

The physical apparatus used for the test is as follows: A webcam is fixed to a certain position on ruler. The head of the webcam is fixed, vertically aligned with reference to its base, and facing forwards in the direction parallel to that of the ruler. At the end of the ruler a small cocktail is attached, propagating from the centre of the ruler width a small distance beyond that of the ruler. This provides a thin fulcrum about which the camera may rotate in the horizontal plane normal to the object plane, which is one of the walls of the room. 

*Image of the camera apparatus used*

*[Fig. 4.2.2]***

The ruler is rested on the top of a table that is horizontally balanced with the markers on the object plane, and at a height such that the camera image is at the same height as the bounded area of the object plane. This reduces the number of positional factors that need to be considered, and that the effect of a single variable can be more easily isolated. 

***Stage 1a: Finding Rotation Parallel To Plane***

***Determining Centres Of Markers***

If, to begin with, the camera image is at both the wrong angle in the plane parallel to the image, and horizontally perpendicular to it, then its position can be corrected one stage at time. To begin with, the angle of rotation parallel to the image plane is compensated found.

In the test example, the first image entered into the prototype system was as shown below on the left. The prototype first identified the boundary markers as shown below on the right:

*The first camera image (left) and the marker mask of the image (right)*

*[Fig. 4.2.3]*

Four sub-masks are then formed from this mask, effectively splitting the mask up into four quarters. The sub-masks are adjusted such that the corner of the quarter is at the origin of the sub-mask (e.g. for the bottom right quarter, the sub-image is flipped horizontally and vertically; for the top right quarter, the image is just flipped horizontally).

The co-ordinates of the centres of mass (and thus the central points of each marker) of each quarter are then located using the method described in section 2.3.4, giving the co-ordinates of the centre of the image from the corner of the image it is closest to:

*(a)			(b)			(c)			(d)*

*Sub-masks of the (a) top left, (b) top right, (c) bottom left, and (d) bottom right quarters of the mask image*

*[Fig. 4.2.4]*

  
    
      ****
      **************
      **************
    
    
      **
      **
      ******
      **
      **
      ******
    
    
      **
      
      
      
      
      
      
    
    
      **
      
      
      
      
      
      
    
    
      **
      
      
      
      
      
      
    
    
      **
      
      
      
      
      
      
    
  

| Quarter | Horizontal distance… (in pixels) | Vertical distance… (in pixels) |
| --- | --- | --- |
| To start of marker block | To centre of marker block | From corner | To start of marker block | To centre of marker block | From corner |
| Top Left | 74 | 20.6 | 94.6 | 29 | 19.8 | 48.8 |
| Top Right | 28 | 16.2 | 44.2 | 53 | 18.8 | 71.8 |
| Bottom Left | 60 | 20.9 | 80.9 | 43 | 19.3 | 62.3 |
| Bottom Right | 37 | 17.6 | 54.6 | 32 | 18.4 | 50.4 |

*Table of centre point positions calculated*

*[Table. 4.2.2]***

 

These results are used to determine the following co-ordinate positions for the centre of the markers in the image as a whole:

  
    
      ****
      ****
    
    
      
      
    
    
      
      
    
    
      
      
    
    
      
      
    
  

| x | y |
| --- | --- |
| 94.6 | 48.8 |
| 275.8 | 71.8 |
| 80.9 | 177.7 |
| 265.4 | 189.6 |

*Coordinates of the centres of the markers, in pixels*

*[Table. 4.2.3]***

These positions are represented on the image below as the red points on the greyscale version of the input image, and the mask used to calculate them:

*(a)					(b)*

*  Coordinates of the centres of the markers, superimposed (a) on mask, and (b) on greyscale version of input image*

*[Fig. 4.2.5]***

   

***Determining Rotation***

It is now relatively simple to determine the plane-parallel rotation of the camera to the object plane. The process is as follows:

Compare the vertical distance between the two points on the left (Left half of image), with the two points on the right (Right half of image). The camera is closer to the side whose points are further apart. In the test case, the two points on the left are further apart.

The points from this half are more accurate representations of the centres of the markers, as the camera is closer to them, and thus their effective resolution in the image is higher. Due to the way the markers are formed, borderlines of a certain number of pixels are created which extend slightly beyond the boundaries of the marker in the original image (Fig. 2.3.10; Fig 2.3.11). The distortion of the marker shape and position due to these borderlines are greater if the marker is smaller; thus the larger (in this case closer) markers provide more accurate estimates of their central positions. These two position co-ordinates on the left side are considered thus those used to determine the angle.

The horizontal displacement between the two points is divided by the vertical displacement, and the tangent of this value if found to determine the angle between the two markers.

If the angle is small (less than one degree in magnitude, in the case of the prototype), then the program passes to the next stage. Otherwise, the angle between the two points is given to the user, together with instructions on what action to take. In the test case, the first input image yields and angle of –6.1 degrees (due to the way positive and negative displacement is defined, and the instruction: 

Rotate Camera in parallel with plane:

6.1

degrees anticlockwise

	is given to the user.

The prototype now waits for the user to reposition the camera, and take a second image. When the user indicates, the prototype loads in the new image, and performs the same analysis on this as it did on the first. In the test case, the new image was:

*Second (position adjusted) image*

*[Fig. 4.2.6]***

This time, the plane-parallel angle was within the one degree acceptable limit (Calculated as –0.3 degrees), yielding the following output:

Rotational Angle OK

The program now passes the image to the next stage.

***Stage 1b: Finding Horizontal Rotation Normal To Plane***

The next stage is to correct the angle of the camera in the horizontal plane normal to the object plane. The process is as follows:

A mask of the image is created:

*Mask of second image*

*[Fig. 4.2.7]***

and the centres of each of the markers are found using the method detailed in section 4.2.2.1. 

The vertical distances between the top left and the bottom left, and the top right and bottom right, marker points are found, and the ratio between them is found. In the test case, the positions of the centres of the four points, with respect to the top left point, are:

  
    
      ****
      ****
      ****
    
    
      ******
      
      
    
    
      ******
      
      
    
    
      ******
      
      
    
    
      ******
      
      
    
  

| Point | x | y |
| --- | --- | --- |
| Top Left | 0 | 0 |
| Top Right | 179.8 | 9.7 |
| Bottom Left | -0.7 | 131.0 |
| Bottom Right | 182.0 | 126.2 |

*Relative positions of marker centres*

*[Table. 4.2.4]***

The left side vertical value is thus: 	131.0 – 0	=	**131.0**	

 	And the right side vertical value is:	126.2 – 9.7	=	**116.5**

**	**The ratio of right over left is:		**116.5** 	 	=	***0.89*********

						**131.0******

Coefficients for a third-degree polynomial are then loaded into the system that allow it to infer a horizontal rotation angle from this ratio. The details for how this is done are given in section 4.4. In the test case, a ratio of 0.89 represents an angle of -16.7 degrees, where the minus sign means the angle is to the left of the normal of the image direction and object plane, in the horizontal plane normal to the object plane:

*Diagram showing meaning of positive and negative angle values*

*[Fig. 4.2.8]*

The real angle of the images was – to within around 2 degrees of accuracy – 17 degrees, so the estimated value is valid. The prototype determines whether  the angle of the camera is acceptable or not. As before, a tolerance value is chosen- this time five degrees- and, clearly, 17 degrees lies outside this tolerance. Thus the code informs the user how far the camera has to be rotated in order for it to be correctly positioned, waits for the user to reposition it and take a new image, and loads the new image.

With the new image, the process repeats again. With the test case, input image, and the mask of the image, are as follows: 

*(a)					(b)*

*The third input image (a), and its marker mask (b)*

*[Fig. 4.2.9]*

This gives marker positions as follows:

  
    
      ****
      ****
      ****
    
    
      ******
      
      
    
    
      ******
      
      
    
    
      ******
      
      
    
    
      ******
      
      
    
  

| Point | x | y |
| --- | --- | --- |
| Top Left | 0 | 0 |
| Top Right | 189.7 | -0.8 |
| Bottom Left | 0.4 | 123.4 |
| Bottom Right | 191.8 | 123.2 |

*New relative positions of marker centres*

*[Table. 4.2.4]*

Which gives a ratio of 1.00, which equates to an angle of 1.09 degrees; acceptable for passing to the next stage.

***Stage 2: Finding Object Disparity***

***Introduction***

Now the camera has been positioned correctly, the prototype needs to determine how far the object (the red rectangle) is displaced from its position in the archive image. In all current (non-archive) images, the object is 6.0mm further to the right, and 4.0mm lower, than it is in the archive image.

In order to determine the disparity of the object, any disparity between the test and archive images as a whole – known as rigid body disparity – needs to be determined. Stage one of the process allows the *angle* of the camera to be corrected relative to the plane, but does not correct the *position* along the axes of the plane from which the camera views the bounded area. 

Once this rigid body disparity has been found, it can be compensated for when performing a digital image correlation (DIC), so that ‘like’ regions – regions of the images common to both archive and current – can be compared.

An object disparity value found by performing a DIC on the common regions of the pair of images, in pixels, then needs to be converted to a value in millimetres, by using a scale found by comparing real-life boundary marker geometries with those located in pixels.

Thus, stage two essentially involves three sub-stages, each of which will now be detailed for the test case in sequence.

***Sub-stage 1: Rigid-body Disparity***

Rigid body disparity, the disparity between two images due to a shift between the images as a whole (rather than displacement of a small-sub region of the image – i.e. the movable object), can be determined in a number of ways: 

If the images are of a flat surface with an amorphous (non-repeating) pattern on it – such as wood-chip wallpaper –, and where any movable objects within the image areas occupy only a small image area, and/or of a low intensity within the intensity plane used, then simply performing a DIC of both whole images should produce an output with the greatest intensity peak at the rigid-body displacement position.

There are a number of problems with this approach: A DIC of the whole image will be affected by both rigid body and object disparity, and may produce a results whose peak is at a position that is a ‘compromise’ between the rigid-body displacement (which should have the greatest ‘energy’ in the image, as most of the features of the image match at this disparity position), and the object displacement. Thus it would produce the wrong value for rigid-body disparity.

Also, most machine work surfaces do not have fixed amorphous patterns on them in a region of interest. Consider a work surface on a drilling machine: Originally, its work surface may be shiny and featureless; over time features on the surface may result in the form of scratches and general wear, but these features are likely to change over time - as more scratches are introduced -, and so cannot be used to determine rigid body disparity between two images taken – for instance – months apart. 

A better method, therefore, may be to use the boundary markers found in the previous stages. This should be more reliable, as they are strong, already identified features, which are not as subject to change in appearance over time than the region actually within the working area.

Thus, in the test case, the rigid-body disparity is found by comparing the boundary marker masks of the current and archive image, rather than the images themselves. 

The image and mask for both the current image and the archive image are as follows:

*(a)					(b)*

*The archive image (a) and the current image (b): Note that the lighting is significantly different for both images, but this does not affect the ability for the computer to identify the boundary markers*

*[Fig. 4.2.10]***

*(a)					(b)*

*The archive mask (a) and the current mask (b): The differences in lighting are compensated for*

*[Fig. 4.2.11]*

This produces the following normalised cross-correlation image:

*Normalised cross-correlation of the two masks: Note the clarity of the main intensity peak*

*[Fig. 4.2.12]*

The position of the peak is identified at x = -20 pixels, and y = 1 pixel. 

This *is* the ***rigid body disparity*** *in pixels*.

***Sub-stage 2: Object Disparity***

Having identified the rigid body disparity, one now needs to identify the displacement of the object *within the plane*, rather than in the images.

The object is located (almost) exclusively in both images by using the technique given in section 2.3.3, giving the following pair of intensity planes:

*(a)					(b)***

*Object colour intensity plane images from (a) the archive image and (b) the current image*

*[Fig. 4.2.13]*

The displacement between the objects in these two images could be considered to the sum of the object disparity, and the rigid body disparity. One could simply determine this disparity, and subtract the rigid body disparity from it to obtain the object disparity; or one could use the rigid body information to form *rigid-body compensated* object images. These images show only the regions of the larger images common to both images:

*(a)					(b)***

*Rigid-body compensated object intensity planes: These images now show only the regions of the original images common to both; rigid-body disparity has been removed *

*[Fig. 4.2.14]*

These images are 20 pixels (the x-axis RB disparity) smaller in width, and 1 pixel (the y-axis RB disparity) smaller in height. As they are smaller, the region containing the object represents a larger proportion of the total image area, and thus has a stronger presence within the image, and produces a slightly more pronounced peak when DIC is used on it:

*NCC of the RB compensated object images *

*[Fig. 4.2.15]*

The position of the peak on this NCC graph (Fig. 4.2.15) is x = 15 pixels, and y = 10 pixels.

This is the recorded value of the object disparity.

One can consider how accurate these values seem by comparing them with the actual object displacement: 6.0mm to the right, and 4.0mm downward. Due to the way Matlab stores images, the origin is taken as the top left corner, thus displacements to the right, and downward, are both positive displacements. Both the x and y object displacement values are positive, which means the recorded object displacement is in the correct direction. 

The ratio between x displacement and y displacement in both cases (actual in mm, and recorded in pixels) is 3/2 (15pixels/10pixels = 6mm/4mm = 3/2), again suggesting that the displacement value found is accurate.

***Sub-stage 3: Real-life Disparity***

The final stage involves converting the pixel disparities into millimetre disparities, by finding the ratio between pixels and millimetres.

The locations of the marker centres on the current image are as follows:

  
    
      ****
      ****
      ****
    
    
      ******
      
      
    
    
      ******
      
      
    
    
      ******
      
      
    
    
      ******
      
      
    
  

| Point | x | y |
| --- | --- | --- |
| Top Left | 68.1 | 54.5 |
| Top Right | 257.8 | 53.7 |
| Bottom Left | 68.5 | 177.9 |
| Bottom Right | 259.9 | 177.7 |

*Positions of marker centres – in pixels*

*[Table. 4.2.5]***

The position of the two horizontal edges – Top right (x) less top left (x), and bottom right (x) less bottom left (x) – are not exactly the same, so a mean is used, to provide an average horizontal edge length in pixels. The same is done with the two vertical edges, giving a horizontal edge value of 190.5 pixels, and a vertical edge value of 123.7 pixels.

From the data provided at the start on real geometry, the real vertical edge distance is 70.0mm, and the vertical edge distance is 50.0mm. Dividing real edge distance by pixel edge distances gives a vertical ratio of 0.40 mm per pixel, and a horizontal ratio of 0.37 mm per pixel. These figures could be thought of as representing the system *resolution*, without resorting to sub-pixel algorithms.

Multiplying the pixel disparities by these ratios gives real-life disparity estimates of 5.5mm (actual: 6.0mm) horizontally, and 4.0mm (actual: 4.0mm) vertically. This gives an overall magnitude of displacement of 6.8mm (actual 7.2mm). Thus the disparity values are accurate to within half a millimetre of the true value, in both the horizontal and vertical axes.

The bounded object plane area was 70.0mm x 50.0mm, or 3500.0mm^2^; the object displacement figure found was accurate to ±0.5mm^2^ (The square root of 0.5^2^ + 0.0^2^). This gives a calculated accuracy level to within 0.5 / 3500, or 0.14 per ***mil****.* Using the 0.40 and 0.37 mm / pixel resolution figures calculated earlier gives a displacement determination accuracy of ±0.54mm^2^, the same value to 1 significant figure. 

***Other Examples***

***Introduction***

Though the example given in the previous section shows how the processes work, it does not show how the processes operate in other conditions.

***Effect Of Non-critical Objects On Identification Of Critical Objects***

In the prototype, two types of object need to be identified: those that mark the boundaries of the area of interest, and the movable object of interest. These are identified by colour. Below, three examples are given where camera position, and movable object of interest are fixed, but other objects – of a non-specified colour – differ in position:

*Test Image 1		Marker Mask			Object Mask*

*[Fig. 4.3.1]***

*Test Image 2		Marker Mask			Object Mask*

*[Fig. 4.3.2]***

*Test Image 3		Marker Mask			Object Mask*

*[Fig. 4.3.3]***

In two of the three cases, the system is able to identify both the markers and the movable object exclusively, without any difficulty. In the third image (Fig 4.3.3), part of a shadow formed by one of the non-critical objects is of a colour and intensity (black), and of a significant enough size, to be wrongly identified as part of a marker. This is a problem specific to greyscale (rather than colour) markers, and again highlights why colour marker colours are often used (Note that the object mask, of a vivid red colour, was successfully and exclusively identified in all three cases). Even this erroneously included portion of the feature could be successfully identified as erroneous by the computer and removed by, for instance, further erosion filtering, or simply (as, in the prototype case, there are just four markers) retaining only the largest object in each quarter of the mask. 

Where erroneously identified objects exist that are of similar or greater size to the correctly identified mask features, a more complicated system - that, for example, determines which of the feature objects identified in the mask is *most likely* to be the real one based on the known marker geometry – would have to be used.

***Effects Of Lighting***

So far, all examples shown have been ones where ambient lighting has been of a normal level; the image was neither dark nor light, and the camera neither over exposed or underexposed. The following images show some of the effects of different types of ambient lighting conditions, including many which are sub-optimal:

*Test Image 1		Marker Mask			Object Mask*

*[Fig. 4.3.4]*

*Test Image 2		Marker Mask			Object Mask*

*[Fig. 4.3.5]***

*Test Image 3		Marker Mask			Object Mask*

*[Fig. 4.3.6]***

*Test Image 4		Marker Mask			Object Mask*

*[Fig. 4.3.7]***

*Test Image 5		Marker Mask			Object Mask*

*[Fig. 4.3.8]***

*Test Image 6		Marker Mask			Object Mask*

*[Fig. 4.3.9]***

A table summarising image descriptions and results is as follows:

  
    
      ****
      ****
      ****
      ****
      ****
    
    
      ****
      **
      ******
      ******
      **
    
    
      ****
      **
      ********
      ******
      **

    
    
      ****
      ****
      **********

      ******
      **

    
    
      ****
      ****
      ******
      **********
      **
    
    
      ****
      ****
      ********
      ********
      **
    
    
      ****
      **
      ********
      ******
      **

    
  

| Image Number | Description | Marker Identification | Object Identification | Comment |
| --- | --- | --- | --- | --- |
| 1 | Normal, constant ambient lighting. | OK | OK | Control Case |
| 2 | Dark /underexposed. Even/ constant lighting. | Not OK – Three erroneous features. Not connected to correct features | OK |  |
| 3 | Dark/ underexposed.
        Uneven lighting. | Not OK – four erroneous features. One connected to marker object | OK |  |
| 4 | Overexposed/ bright.
        Even lighting (directly from behind) | OK | Not OK – 
        Not identified | Marker mask is sharp |
| 5 | Overexposed/ bright.
        Uneven lighting (from bottom left hand side) | Not OK – One feature erroneously identified | Not OK – Object correctly identified, but brightest corner of image also erroneously identified as image | Objects connected to image corner or edge can be identified as erroneous and removed |
| 6 | Uneven lighting, partially bright, partially dark | Not OK – One feature erroneously identified | OK |  |

*Table of lighting effects on object identification*

*[Table. 4.3.1]***

As stated previously, using a greyscale marker represents a worst-case scenario regarding ease of identification. This shows in these results, where the shadow formed by one particular non-critical object, near the top right of the bounded area, is erroneously identified in almost every marker mark of the image with sub-optimal lighting. In images 2 and 3, even more objects are included erroneously. In no cases, however, are the correct objects not *identified,* and only in image 3 does an erroneous feature ‘bleed’ into a marker (making removing erroneous features exclusively more difficult). 

In comparison, the red object was correctly and exclusively identified in almost all cases. When the camera was greatly overexposed (Image 4), the program was unable to differentiate between the object and its background, and thus it was not identified. In the other case (Image 5), part of the edge of the image was overexposed, and incorrectly identified. However, as the object is known to not be on the edge of the image, and the erroneous feature was not connected to it, the erroneous feature could identified as such and removed quite easily.

The results of image 4 are important, as, in this case, the markers were easily identified. This type of image could be created by either increasing the contrast of the camera, or by switching on a portable light source behind the camera. This would have the effect of removing the effect of uneven lighting on creating erroneous feature identification (such as in image 5), and more easily than attempting to *block* light. Afterwards, the light source could be de-activated to allow the red object to be identified.

In a more general case, a strong light source that makes features of a certain colour more prominent could be used to make identifying that particular feature easier.

***Effects Of Camera Distance***

So far, all tests have been conducted at a single distance (154mm). The following table shows the effect changing the distance has on the calculated ratio of right side vertical distance between markers to left side distance- used to calculate the horizontal plane angle of the camera to the object plane – at 30 degrees to the left of the normal angle. 

  
    
      ****
      ****
      ****
    
    
      ******
      
      
    
    
      ******
      
      
    
    
      ******
      
      
    
    
      ******
      
      
    
    
      ******
      
      
    
    
      ******
      
      
    
  

| Distance (mm) | Ratio (RHS / LHS) | Relative Ratio |
| --- | --- | --- |
| 154 | 0.86 | 1.00 |
| 174 | 0.87 | 1.02 |
| 194 | 0.88 | 1.03 |
| 214 | 0.89 | 1.03 |
| 234 | 0.89 | 1.04 |
| 254 | 0.90 | 1.05 |

*Table of effect of distance on calculated ratio*

*[Table. 4.3.2]*

*Masks used to calculate ratios at same angle and different distances*

*[Fig. 4.3.10]***

As one can see, as the distance increases, the ratio tends towards 1. This makes sense due to the effects a limited resolution has on the way an object is interpreted at different distances. As the object gets further away, more information about it is lost, and less can be interpreted about it. Even looking at the masks of the images, they start to appear more rectangular when smaller, and this effect is resulting in the increasingly inaccurate ratio results.

It would be possible to use the actual number of pixels between markers, and the size of markers in the images, to estimate the distance from the camera to the plane, and thus the accuracy of other figures such as estimated angle. 

In DIC, is important that the two images to be correlated are at the same distance (as well as angle). Thus, a final system would need to be able to determine and inform the user of its distance from the plane, as well as angle to it.  

***4.4	Calibration***

For stage 1b, it was required that the prototype device be able to determine an angle from a ratio. This required prior calibration: 10 sets of 17 images, at a set distance and horizontal plane angles varying incrementally from –40 degrees to 40 degrees in 5 degree steps, were taken, and the ratio between left vertical edge and right vertical edge (as in the previous example) were found. 

The average value at each of these angles, from all 10 cases, was found, giving the following results when plotted against angle:

*Graph of ratio to angle*

*[Fig. 4.4.1]*

A third degree polynomial approximation, equating ratio to angle, was found, and the coefficients generated stored. The Matlab functions *polyfit *and *polytool* were used, and the red lines on the above graph show the *polytool* estimated error level of the polynomial fit to the real values. These are loaded into the stage 1b code, and used to calculate the horizontal plane angle.

The coefficients, in descending order, are: **272.6;   -914.3;	1,152.0;   -509.9**

i.e. [*equation*]{.eqn-ref} *[Eqn. 4.4.1]*

As an example, the ratio value 1.08 (r = 1.08) leads to an angle (θ) estimate of 11.2 degrees. Using r = 1.04 yields θ = 5.9 degrees.

*Negative angle*

*Positive angle*

**Object plane**

