---
title: "Chapter 4: The Rise of Formal Paid Work"
---

Chapter Four will consider the rise of formal, paid work and the relationship between this process and more general societal changes. The argument will be developed that changes in society lead to the emergence of increasingly formalised and comprehensive systems of social security and welfare provision.

Chapter Five will discuss the historical and contemporary role of the mechanisms described in chapter two – the rationalisation and formalisation of political decision-making processes – in political responses to employment and welfare.

Introduction

Preamble and Review

The author lives on the first floor of a flat at the edge of the city of York. When he takes a coffee break, he can see part of two of the walls which surround the city, connected by one of the gates. If one walks underneath this gate and towards the York Minster cathedral in the centre, one comes across a number of ancient buildings constructed by institutions and organisations which existed many centuries ago. Amongst these, The Merchant Adventurers’ Hall, approached via an alleyway in Fossgate. 

	

The first chapter in this thesis considered, in a very broad sense, how changing material circumstances lead to pronounced changes in social structure; in particular, how increased population density tends to lead to increased social inequality and the formation of a proto-political ‘elite’. 

The second chapter considered how this social elite could, in combination with certain historical circumstances and technological developments, begin to transform itself into a bureaucratic system: multiple-tier hierarchical structures of political, centralised, command-and-control, which administrate and rule, more directly than before, over increasing numbers of people at living over increasing geographical distances. Developing from the classical sociology of Max Weber [ref], it was suggested that bureaucratic systems differ from previous systems of multi-tiered government in the extent to which governmental practices are formalised and rationalised, allowing the system to continue to operate even when all of the individuals involved in the system are replaced. 

The third chapter presented a number of theories of social interaction based upon the ‘substantivist economic’ position espoused by Karl Polanyi within *The Great Transformation* [ref]. This sought to demonstrate the necessity of recognising the importance of social relationships to economic behaviours, and to present an economic discussion of social relations which emphasised the etymological meaning of the term ‘economics’ as ‘household management’. 

Aim and format of this chapter

This chapter will link a number of the concepts developed within previous chapters to contemporary forms of social structures within modern Britain. A form of evolutionary-structuralist position will be adopted, in that arguments will be presented suggesting how some of the archaic social structures hitherto discussed could have, under certain kinds of selective socio-economic conditions, evolved into the kinds of social structures presently and readily observed. 

	The chapter will concentrate on attempting to explicate the sorts of practical ‘logic’ underlying socio-structural evolutionary changes. To this end the main text within the chapter will develop arguments of the logical reasons for certain forms of social-structural changes, whereas footnotes and endnotes will used to detail historical evidence for such patterns of change, and other writers who have developed arguments compatible with those explicated in this chapter. 

	As part of this emphasis on the underlying logics of socio-structural changes, the focus will be on *processes, *rather than *events.* However, the discussion of such processes will be developed primarily by presenting representations of different forms of social structure, which characterise (in the Weberian sense of ‘Ideal Types’) idealised stages through which a social structure passes as a result of changing historical circumstances. This is because changes cannot, in-and-of themselves, be observed or easily imagined. The manifestations of change, however, can be.

	As part of the evolutionary theme of this chapter, *rival* (idealised) social structures will be presented. Donald T. Campbell suggested that evolution, in a general sense, could be considered ‘random variation and selective retention’ [Ref]. The purpose of presenting rival social structures is thus to suggest two important variants, and how selective pressures may led one variant to be retained at the expense of the other. 

Types and ‘logics’ of change

Merchant-Adventurers

The first chapter suggested that agricultural systems of food production have a tendency to produce social elites, who hoard resources produced by commoners, in exchange for offering various forms of securities and ‘protection’. One of the advantages of being an elite, rather than a commoner, would be increased ability to marshal resources directed towards a particular goal. One important goal of social elites is to acquire scarce, ‘positional’ goods. The value of such goods are inherent in their scarcity, and the ability to acquire positional goods does the (for elites) important relational work of signifying social and material advantage – ‘distinction’, to use Pierre Bourdieu’s term [ref]– over others (both commoners and, in  the case of multi-tier elite structures, other elites). The more expensive, in terms of resources required to acquire, a good is, the more it signifies social distinction, and the more effective it is as a positional good. 

	In pre-industrial times, it was outside of the material capabilities for most people (Commoners) to 1) acquire ‘exotic’ material goods (i.e. goods produced in places that are difficult to reach); and, 2) travel long distances. Travelling long distances was prohibitively costly for most people because travelling outside of the town or city in which one lived tended to be very dangerous unless one travelled as a well-provisioned group. When most people in a community barely have the resources to subsist, being able to demonstrate that one has such an excess of resources as to survive outside the welfare support network of the community, and instead travel beyond the threshold of the town, is to clearly demonstrate one’s social advantage. 

	The Travelling Party could thus, perhaps, be considered an important social structure, whose existence requires only positing a sedentary Landed Elite with surplus resources, and a desire to maintain their social position through displays of conspicuous consumption.

	Once one accepts that Landed Elites may beget Travelling Parties, who form under the (often unconscious and unstated) motivation to demonstrate their social advantage, it seems unproblematic to assume that some or many Travelling Parties may take resources from distant places in order to demonstrate the extent of their travels. As well as serving as proof of the distance the Party has travelled, the materials also become valuable as ‘exotic goods’. In both cases, the goods do similar forms of positional work. 

	What, and whom, Travelling Parties encounter helps determine whether they come to adopt one of a variety of other social structures. If they encounter a new form of valuable, exploitable natural resource – such as a fresh water source – then they could become founders of 

	

plausible goal is travel; another, related goal, is the acquisition of scarce goods which emphasise the distinction the 

Walls

Notes

Elements to consider

	the rise of formal, paid work

	general societal changes

		Urbanisation

			Specialisaton

			Higher Population Densities

	the relationship [between formal, paid work] [and general societal changes]

The argument will be developed that changes in society lead to the emergence of increasingly formalised and comprehensive systems of social security and welfare provision.
