---
title: "Chapter 3: Work, Sickness, and Community"
---

*Chapter Three: Work, Welfare, Community and the Sociology of Economies***

[T]he significant thing about [political] rights is not that they should exist in the abstract, but that the state, rather than some other organization, should become the focus of their enforcement. Indeed, rather than thinking of abstract rights which are enforced (or violated) by states, it would be more illuminating to think of political rights as claims binding the agents of the state to specific groups of people: religious minorities can call on the state to defend them from persecution, adult citizens can insist the state give them their day in court, the indigent can claim sustenance from the state. These are political rights in a large sense – political in that they constitute binding claims on the agents of government, rather than on some other group. 

[1][pp.  36-7]

[I]n the long run, all social obligations are reciprocal. 

[2][p. 48]

Introduction

The purpose of this chapter is to consider welfare economics in a very broad sense. 

The breadth with which the term ‘economy’ may legitimately be considered and interpreted is suggested by its etymology: from the Greek *oikonomia*, meaning ‘household management’. [[3] pp 453-4] Most of the books that the modern discipline of economics trace their lineage to,  for example Adam Smith’s *The Wealth of Nations* [4], were originally described as works of ‘political economy’ rather than simply ‘economics’. Their concern could thus logically be assumed to be that of ‘managing the political household’, rather than (for example) the creation of axioms asserting the behaviour of ‘economic agents’ (and the assertion and implication that such economic agents behave very much like human beings).

	The approach the author will adopt to economics within this chapter is that advocated by the economic historian Karl Polanyi, in books such as *The Great Transformation *[2] and *The Livelihood of Man *[5]. This approach is known as ‘substantivism’, and asserts that economics *should* involve investigating and describing processes by which people provide for the needs of themselves and those with whom they are associated; economics, in this sense, is thus primarily a study of *provisioning,* and is, within contemporary parlance, ‘stakeholder focussed’. Within *The Great Transformation*, Polanyi suggested that modern economics had come to adopt too much of an individualistic, rather than communalistic, perspective on the nature of economies, reflecting too exhaustive and exclusive a focus, amongst conventional economists, on social activities within the eighteenth and nineteenth centuries. “The corrective of such a ‘short-run’ perspective”, Polanyi wrote, “would obviously have been the linking up of economic history with social anthropology”, but states that this course has been “consistently avoided.” [2][p. 47] 

	Given the discussions within, particularly, the last part of chapter one and the first part of chapter two, which together sketched an aetiology of modern state formation, Polanyi’s proposed synthesis hopefully appears consonant with our investigations. The purpose of this chapter is thus to ‘humanize’ economics somewhat, as per Polanyi’s suggestions, and present an economic perspective that takes on board the anthropological and sociological concepts which have already been presented, *such that the primacy of social relationships to economic practice is made much more explicit*.

Chapter Outline

The chapter will proceed as follows: Firstly, Polanyi’s discussion of pre-market economies will be introduced and summarised. This discussion will be related to the Diamond’s schema discussed in chapter one. Then, it will also be used to introduce and explore two other, related concepts, in greater depth: firstly, that of the importance of *reciprocation* to effective social relationships (in the very broad economic sense adopted here); and secondly, that of social differentiation and categorisation, and the effect such differentiation has upon economic behaviours. Implications and corollaries of these two concepts will be discussed.

Throughout the chapter, the extent to which almost all economic behaviours can be conceived of as fundamentally about ‘welfare’ should become apparent; the chapter will conclude by making this association explicit.

Polanyi’s Economies of Substance

Broadly, the proposition holds that all economic systems known to us up to the end of feudalism in Western Europe were organized according either on the principle of reciprocity or redistribution, or householding, or some combination of the three. These principles were institutionalized with the help of a social organization which, inter alia, made use of the patterns of symmetry, centricity, and autarchy. In this framework, the orderly production and distribution of goods was secured through a great variety of individual motives disciplines by general principles of behavior. Among these motives gain was not prominent. Custom and law, magic and religion cooperated in inducing the individual to comply with rules of behaviour which, eventually, ensured his functioning in the economy system. [2][p. 57]

This chapter section will proceed by attempting to unpack the meanings, theories and assumptions within the above paragraph. The paragraph summarises Polanyi’s substantivist position on economic theory relatively succinctly; however, as with an introductory paragraph from Damasio used in chapter one, which evokes a specialised usage of the terms ‘image’ and ‘object’, the above paragraph is only succinct through its use of certain terms in a relatively specific and narrow sense, which differ slightly from the more general and vernacular uses to which the terms are more usually employed. 

	The terms in question are: ‘reciprocity’, ‘redistribution’, ‘householding’; and ‘symmetry’, ‘centricity’, and ‘autarchy’. A complete reading of the chapter of *The Great Transformation* in which these terms are introduced and discussed, ‘Societies and Economic Systems’ [2][pp. 45-58], makes it clear that the terms are associated as follows:

  
    
      ****
      ****
    
    
      
      
    
    
      
      
    
    
      
      
    
  

| Economic System | Social Relationship |
| --- | --- |
| Reciprocation | Symmetry |
| Redistribution | Centrality |
| Householding | Autarchy |

Each form of economic system is thus dependent upon a particular form of social arrangement; as Polanyi puts it:

The outstanding discover of recent historical and anthropological research is that man’s economy, as a rule, is submerged in his social relationships. He does not act so as to safeguard his individual interest in the possession of material goods; he acts so as to safeguard his social standing, his social claims, his social assets. He values material goods only in so far as they serve this end. [2][p. 48]

By now, it is expected that the reader will have noticed the close correspondence between the communalistic economic position advocated here by Polanyi, and much of the anthropological discussion within the latter part of chapter one. As the author stated in chapter one, it seems logical to assume that, as a mortal being, the initial and primary requirement that individuals place upon an economic system are to ensure that the system minimises the probability of experiencing such severe levels of privation as to threaten survival. As previously suggested, in small tribal groups, the fate of the individual is generally recognised to be the fate of the community; the risk of a venture failing to produce a required good (such as some form of fuel or clothing) is large enough that, if each individual member of the tribe did not share the spoils of success, he or she would not be able to call upon a network (or ‘figuration’) of social reserves to prevent privation when ventures fail. “The individual’s economic interest is rarely paramount, for the community keeps all its members from starving unless it is itself borne of a catastrophe, in which case interests are again threatened collectively, not individually.” [2] [p. 48]

Both ‘reciprocity’ and ‘redistribution’, as Polanyi uses the terms, are relatively simple economic strategies, but can allow complex economic relationships to emerge. Given the requisite social relationships of, respectively, symmetry and centricity,  “[r]eciprocity and redistribution are able to ensure the working of an economic system without the help of written records”. [2] [p. 51] These two economic principles of reciprocity and redistribution were, Polanyi writes, overwhelmingly responsible for some highly complex economic arrangements: “The Kula ring, in western Melanesia, [was] based on the principle of reciprocity; and redistribution was present on a gigantic scale in the civilization of the Pyramids.” [2] [p. 52]

Redistribution as Reciprocity

Within the above discussion, ‘reciprocity’ and ‘redistribution’ have been presented as separate forms of economic behaviour, the former dependent upon a social pattern of symmetry, and the latter upon a social pattern of centrality. (Chapter One provided more involved discussion as to why and how ‘redistributive’ social arrangements came after ‘reciprocal’ social arrangements.) 

Briefly, however, and as the quotations at the start of the chapter allude to, it may be useful to consider both ‘reciprocity’ and ‘redistribution’, as Polanyi terms it, as specific forms of a more general form of reciprocation. To do this, the following lexicon should be adopted:

  
    
      ****
      ****
    
    
      
      
    
    
      
      
    
  

| Polanyi’s Term | Author’s Term |
| --- | --- |
| Reciprocity | Horizontal Reciprocation |
| Redistribution | Vertical Reciprocation |

Though this lexicon may appear simply to be adding another unnecessary layer of terminology to the discussion, the author believes it important to highlight the extent to which reciprocation, in the broadest sense, is at the heart of effective socioeconomic relationships. The author would even go so far as to assert that *the principle of reciprocation is as important to understanding social phenomena as the principle of induction is to understanding physical phenomena.*

	Recognising that redistribution is a form of reciprocation between unequals, just as reciprocity is a form of reciprocation between equals, helps clarify why social disparities in power are tolerated. Elites often, and successfully, justify their position over commoners by offering something in return: this is the form of reciprocation of rights and obligations described in this chapter’s introductory paragraph. Heuristically, the greater the benefits the elite can offer, or appear to offer, the commoner in exchange for submitting their personal autonomy, the greater the level of control the commoners will allow the elites to cede. The two most precious guarantees elites can make to commoners is to save them from premature death, either through warfare or starvation: two of the most fundamental goods imaginable. With respect to the former – preventing premature deaths at the hands of others – the introduction to the 1975 edited volume “The Formation of National States in Western Europe” includes the following:

Possibly most striking and disturbing is the finding of the authors of this volume that wars and threats of war played such a critical part in building the strong states of Europe. The ominous phenomenon of war gave telling reality and unquestionable legitimacy to the reasons of state. What was established and learned in the mobilizing of resources for national security persisted to provide funds for peacetime allocations, largely because of the extraordinary ratchet effect universally inherent in the processes of taxation. 

One should also not forget the extent to which much of the modern British welfare state has its origins in state planning initiatives during the Second World War. 

	With respect to the latter, food, it should be noted that one of the main arguments within *The Great Transformation *is to do with asserting the popularity of a strategy amongst British feudal elites of placating their commoners:

The justices of Berkshire, meeting at the Pelican Inn, in Speenhamland, near Newbury, on May 6, 1796, in a time of great distress, decided that subsidies in aid of wages should be granted in accordance with a scale dependent upon the price of bread, so that a minimum income should be assured to the poor *irrespective of their earnings.*

The measure was successful, and lasted for almost forty years. What the peasants asked of God, the feudal elites provided: 

[I]t became the law of the land over most of the countryside, and even, in a much diluted form, in a number of factory towns; actually it introduced no less than a social and economic innovation than the “right to live,” and until abolished in 1834, it effectively prevented the establishment of a competitive labor market. 

Food and physical protection are examples of some of the most fundamental goods elites can offer commoners in order to establish and embed themselves in stable bonds of vertical reciprocation. The paragraph quoted from the start of this chapter suggests that successful elite groups often extend these initial bonds into a complex figuration of agreements and arrangements with particular interest groups. With respect to the discussions, in chapter two, of the growth of legal institutions and state-based nationalism, it could be inferred that a major development in the growth of the modern state has been the categorisation and formal recognition of very large numbers of territorially bound people as a very broad, single ‘interest group’ of commoners, known as ‘subjects’ or ‘citizens’, who are understood to be engaged in a reciprocal bond – of rights and responsibilities- with the elitist structure known as ‘the state’. The formalisation and standardisation of the complex figuration of vertical reciprocal arrangements appears to be the basis of much ‘contractarian’ thinking in political philosophy, for example [some examples]; however, such contractarian theories tend to disregard the extent to which vertical reciprocation emerged tacitly through habitual patterns of interpersonal behaviours, and did not tend to begin with rational discussions and agreements.     

An Aside on the Psychology of Reciprocation

Despite receiving scant attention within much of the quantitative social sciences, the principle of reciprocation is recognised as highly important within much of modern psychology [refs?]. For example, Robert Cialdini, a professor of psychology, writes that: “By virtue of the reciprocity rule ... we are *obligated* to the future repayment of favors, gifts, invitations, and the like.” [6] [p. 18] Cialdini continues:

The impressive aspect of the rule for reciprocation and the sense of obligation that goes with it is its pervasiveness in human culture. It is so widespread that after intensive study, sociologists such as Alvin Gouldner can report that there is no human society that does not subscribe to the rule. And within each society is seems pervasive also; it permeates exchanges of every kind. Indeed, it may well be that a developed system of indebtedness flowing from the rule for reciprocation is a unique property of human culture. The noted archaeologist Richard Leakey ascribes the essence of what makes us human to the reciprocity system: “We are human because our ancestors learned to share their food and their skills in an honoured network of obligation,” he says. Cultural anthropologists Lionel Tiger and Robin Fox view this “web of indebtedness” as a unique adaptive mechanism of human beings, allowing for the division of labor, the exchange of diverse forms of goods, the exchange of different services (making it possible for experts to develop), and the creation of a cluster of interdependencies that bind individuals together into highly efficient units. [6][p. 18]

Cialdini is also a professor of marketing, and suggests that the reciprocal principle is also well recognised, and exploited, within much of the commercial sector, which employs a variety of ‘tricks’ and techniques based on the principle (including, Cialdini suggests, ‘free gifts’) in order to persuade customers to buy goods and services they would not otherwise have bought. [6][pp. 17-56]

	Cialdini suggests that there is often an urge amongst recipients of gifts to consider the importance of paying back a ‘symbolic debt’ above the monetary value of the items exchanged.  This allows gift-givers to suggest an unequal framework for reciprocation which is to the recipient’s financial disadvantage, and which the gift-recipient will be liable to accept. In the short-run, this means the gift-giver can exploit the recipient. In a small community where all members were likely to be engaged in long-term associations with one another, such initial advantages would only be temporary, but in a society of strangers this technique can be exploited systematically but ruthless salespeople looking to improve their sales figures.

Householding: the economics of categorical thinking

Within our consideration of vertical reciprocation, the author discussed the idea that political rights emerge as forms of vertical reciprocal agreements between the state and specific groups. However, the author did not go into any detail or discussion as to how such specific groups emerged. Understanding the emergence and importance of ‘groupness’ to social behaviour is important if one is to understand Polanyi’s third economic principle, *householding*, which “consists in production for one’s own use.” [2][p. 55] On householding, Polanyi writes:

[W]e should not assume that production for a person’s or group’s own sake is more ancient than reciprocity or redistribution. On the contrary [...] [T]he practice of catering for the needs of one’s household becomes a feature of economic life only on a more advanced level of agriculture[.] [2][p. 55]

This ‘logic of practice’ behind this assertion becomes clear if one considers the second part of chapter one, and Diamond’s assertion that the single strongest predictor of societal complexity is population size [cross-ref]. Diamond suggests that moving from hunter-gatherer systems of food procurement, to agricultural systems of food production leads both to higher food yields – the same amount of land being able to sustain many more people; and to a more sedentary rather than nomadic living arrangement. These factors lead to higher population densities and, according to Diamond, a ‘geometrically’ increasing probability of two individuals encountering each other who do not share a common background of experience and interests.  Once the size and density of a population increases beyond a certain level, householding – the propensity to relate and share with some people far more than others - becomes an important economic principle in its own right. 

Householding could be thought of as the result of a timeless and universal social inclination – that of categorising and demarcating between ‘ingroup’ and ‘outgroup’ – interacting with a much more historically contingent social circumstance: having to live peacefully in a high density population with many people whom one does not know.  The different behaviours an individual  adopts towards those whom she perceives as ‘one of us’, and towards ‘one of them’, have been the focus of a great deal of sociological and social psychological investigation [refs]. The processes and ease with which social groups emerge, come to have emotional salience for members, and affect inter- and intra-personal relationships have also been investigated in some detail. This chapter will now look at some of this research.

Insights from Social Psychology

In her book *The Nurture Assumption*, Judith Rich Harris makes the following provocative suggestion:

The basic phenomena of group relations ... – preference for one’s own group, hostility toward other groups, between-group contrast effects, and within-group assimilation and differentiation – are so robust, so easy to demonstrate in the laboratory or observe in natural settings, that social psychologists soon found themselves with little left to do but clean up the crumbs. *It was the success of social psychology, not its failure, that led to the decline of the field in the wake of the brilliant research carried out in the 1950s.* [8] [ p. 136]

The purpose of this chapter section is to investigate some of this ‘brilliant research’, and see what implications the field has to the kinds of social and economic behaviours Polanyi refers to as ‘householding’. 

Schemas

To begin with, it may be useful to first consider a relatively general and accessible discussion of some of the cognitive aspects of social judgements and decision-making, from Richard Nisbett and Lee Ross’ 1980 book *Human Inference: Strategies and Shortcomings of Social Judgment [9]*:

To understand the social world, the layperson makes heavy use of a variety of knowledge structures normally not expressed in propositional terms and possibly not stored in a form even analogous to propositional statements. In describing these cognitive structures we shall use the generic designation “schema” and will comment in detail about only two types of schemas  - event-schemas, or “scripts,” and person-schemas, or “personae.” [[9] p. 32]

Nisbett & Ross describes the former variety of schema, ‘scripts’, as follows:

A script is a type of schema in which the related elements are social objects and events involving the individual as actor or observer. ... [S]cripts generally are event sequences extended over time, and the relationships have a distinctly causal flavour, that is, early events in the sequence produce or at least “enable” the occurrence of later events. [[9] p. 34]

The compatibility and association between the notion of ‘script’ presented here, and the discussions of Damasio, James and Bourdieu in the first part of chapter one, should be obvious. 

On the second type of schema, the ‘persona’, Nisbett & Ross write:

Social judgements and expectations are often mediated by a class of schemas which we shall term “personae,” that is, cognitive structures representing the personal characteristics and typical behaviors of particular “stock characters.” Some persona are the unique products of one’s own personal experience (good old Aunt Mary, Coach Whiplasch). Others are shared within the culture or subculture (the sexpot, the earth-mother, the girl-next-door, the redneck, the schlemiel, the rebel-without-a-cause). Many of the shared personae are borrowed from fiction (Shakespeare’s tortured Hamlet ...) or even from the popularized professional jargon or psychology and psychiatry (the authoritarian, the “Type A” personality, the anal-compulsive). [[9] p. 35]

Thus, in everyday social situations, we have a tendency to think in terms of rich, obdurate ‘characters’ (rather than more abstract and intangible structures like features of statistical models). As Nisbett & Ross state:

[T]he persona constitutes a knowledge structure which, when evoked, influences social judgments and behaviors. Once the principal features or behaviours of a given individual suggest a particular persona, subsequence expectations of and responses to that individual are apt to be dictated in part by the characteristics of the persona. [[9] p. 35]

Stories

Within sociology, the scripts-and-personae position has its corollary in what Charles Tilly calls ‘stories’: one of the four approaches to reasoning ‘why’ Tilly suggest people adopt within different circumstances. When non-specialist people talk about events that are “puzzling, unexpected, dramatic, problematic, or exemplary” [[10], p. 69], they are liable to explain the events through stories. Tilly summarises the key features of stories as follows:

  - People will usually tell stories to explain the events in question, they won’t settle for general principles (“Pride goeth before a fall”) or conventions (“She’s just unlucky”), even if they end their stories with general principles or conventions.

  - The stories will have no more than a handful of characters, will include a small number of actions by those characters, will treat what happened as effects of those actions, and will take place within a single time and place.

  - Actors’ dispositions (rather than, say, pure accident or fate) will cause most or all of their actions.

  - Dispositions will figure even more centrally when the narrator is the central actor.

  - The stories will omit a large number of likely causes, necessary conditions and, especially, competing explanations of whatever happened. 

  - A few master stories – A let B down and B suffered, C and D fought to a standstill, and so on – will recur, so much that listeners will often guess what comes next.

  - The stories will usually have some kind of moral, or at least by assigning praise or blame to one or more of the characters.

  - Questions that challengers raise will much more often concern attributions of praise, blame, or disposition (“Are you sure that’s what he meant?”) than the overall cause-effect structure of the story.

  - The exact conventions and idioms that storytellers use, however, will differ distinctly between the settings. [[10], pp. 69-70]

To combine the terminologies of Tilly with Nisbett & Ross, stories are attempts at generalised social causal reasoning comprising almost exclusively of scripts (conventions and master stories) and personae (the actors, with their strongly influential dispositional tendencies). Social judgement thus depends very much on thinking ‘categorically’ about other people, and the assumption that individual dispositions have much greater influence on their behaviours than does their general situation. People tell each other stories to try to explain why people are what and where they are.

The Ingroup and the Outgroup

Although there is a great deal of richness and variety to the personae people develop and utilise in making social judgements, there does appear to be a  categorical distinction more fundamental than all others: whether someone is an ‘us’, or a ‘them’. Within social psychology, the two categories of this dyad are known simply as the ‘ingroup’ and the ‘outgroup’.

	The propensity for people to divide themselves into ingroup and outgroup appears so strong that it can be initiated very easily within experimental (and also natural) settings: any initial, even random, and systematic difference between persons can be used to generate a salient sense of groupness and group demarcation. These salient, group identities then have a significant effect upon the ways group members behave towards members of their own ‘ingroup’, and towards the other ‘outgroup’.

	Some of the most well-known experiments in the social psychology of group formation and differentiation – such as Muzafer Sherif’s ‘Robber’s Cave Experiments’ – used subjects drawn from the same demographic categories, and with apparently similar physical and cultural attributes,  in order to ensure that subsequent group categorisations were the result of experimenter influence rather than pre-existing conditions. Subsequent, systematic differences in the performance of the groups could thus be attributed to the effect of ‘groupness’ itself, rather than on systematically different qualities and characteristics of the individuals who comprised the groups. 

	This attempt to differentiate group effects from other effects reached its *reductio ad absurdum *in a series of experiments conducted by Henri Tajfel that helped develop what is now known as the Minimal Group Paradigm. This involved dividing a homogeneous set of individuals in ways which were explained and demonstrated to be of little rational importance as evidence of genuine, systematic difference between group members. In Tajfel’s own words:

The general principles of this minimal imposition are simply stated: the subjects are divided into two ‘groups’ on the basis of criteria which are assumed to be quite unimportant to them (such as expressive a preference for one or the other of two painters they have never heard of before – although in reality the subjects are randomly assigned to one or the other ‘preferences’ groups, and the paintings of which they see the reproductions on slides are also randomly designated as being by one or the other painter). The subjects do not interact during the experiment, either within or between the ‘groups’. Each subject is informed of his own group membership based on his preferences but the membership of all other subjects, whether in his own group or in the other, remains anonymous to him. Each subject is then isolated for a short time when he is asked to make decisions through which he allots various amounts of money to two *other* subjects only designated by individual code numbers and by their respective group membership. [11] [pp. 233-4]

The apex of this ‘minimal imposition’ was reached in a permutation Tajfel conducted in 1973:

In the experiment of Billig and Tajfel (1973), the height of absurdity was reached in the method used to divide the subjects into ‘groups’. Even the pretence of differences between the groups in aesthetic preferences was dropped, and each subject was explicitly and visibly assigned to one group or the other on the basis of a random toss of a coin. [11] [p. 234]

However, even though subjects knew or believed the reasons for their group allocation to be trivial or even completely arbitrary, the influence such group allocation had upon social behaviours and intergroup discrimination was profound:

[A] variety of measures have shown that, in these initial experiments as well as in all the others which followed them, most of the subjects acted very consistently in the direction of favouring in their decisions anonymous members of their own groups at the expense of the anonymous members of the outgroups. [11][p. 234]

The Minimal Group Paradigm demonstrates that, even when stripped of genuine systematic underlying difference and the contingent circumstances of social history, the effect of ‘groupness’ in-and-of-itself can function as a  major contributing factor to the perpetuation of inequalities across groups. For this reason, the paradigm, and related ideas and research on group psychology, do much to explain the reason why Householding came to be, and remains, such a vitally important economic principle. 

	Although Tajfel was the first person to give the Minimal Group Paradigm a specific name, the importance of the tendency was recognised long ago:

[The two great empires of *Lilliput* and *Blefuscu*] have ... been engaged in a most obstinate War for six and thirty Moons past. It began upon the following Occasion. It is allowed on all Hands, that the primitive Way of breaking Eggs before we eat them, was upon the larger End: But his Majesty’s Grandfather, while he was a Boy, going to eat an Egg, and breaking it according to the ancient Practice, happened to cut one of his Fingers. Whereupon the Emperor his Father, published an Edict, commanding all his Subjects, upon great Penalities, to break the smaller End of their Eggs. The People so highly resented this Law, that our Histories tell us, there have been six Rebellions raised on that Account; wherein one Emperor list his Life, and another his Crown. These civil Commotions were constantly formented by the Monarchs of *Blefuscu;* and when they were quelled, the Exiles always fled for Refuge to that Empire. It is computed, that eleven Thousand Persons have, at several Times, suffered Death, rather than submit to break their Eggs at the smaller End. [7][pp. 30-31]

First published in 1727, the conflict between the Lilliputians and Blefuscutions is generally recognised as an allusion to then-contemporary wars between England and France over different ways of practicing Christianity.

	

Durable Inequality

The previous section described social and cognitive psychological processes by which individuals make social judgements about others based upon categorical thinking and group identities. This section will now suggest how such principles appear to underlie much of Charles Tilly’s theory of “Durable Inequality” [12]. 

	Within his book, Tilly describes a number of social patterns by which some people come to consistent possess more ‘goods’ than others. Tilly defines in a very general sense, including “not only wealth and income but also such various benefits and costs as control of land, exposure to illness, respect from other people, liability to military service, risk of homicide, possession of tools, and availability of sexual partners” [12][p. 25]. All of these patterns can be attributed to group behaviours, rather than purely individual level behaviours. 

Introduction

Tilly states his theories attempt to build “a bridge from Max Weber on social closure to Karl Marx on exploitation, and back.” [12][p. 7]  (Tilly uses the term ‘opportunity hoarding’ more or less as a synonym for the term ‘social closure’[?]) He states that the “book concerns social mechanisms – recurrent causal sequences of general scope – that actually lock categorical inequality into place” [p. 7]

The central argument runs like this: Large, significant inequalities in advantages among human beings correspond mainly to categorical inequalities in advantages among human beings correspond mainly to categorical differences such as black/white, male/female, citizen/foreigner, or Muslim/Jew rather than to individual differences in attributes, propensities, or performances. In actual operation, more complex categorical systems involving multiple religions or various races typically resolve into bounded pairs relating just two categories at a time, as when the coexistence of Muslims, Jews, and Christians resolves into the sets Muslim/Jew, Muslim/Christian, and Jew/Christian, with each pair having its own distinct set of boundary relations. [12][p. 7]

Dyads

The categorical distinctions thus divide persons into one side or another of a categorical dyad. It appears that, within the dyadic schema, the set, the categories are considered, in formal parlance, exhaustive and disjoint: you’re either a Muslim or a Jew, Right-wing or Left-wing, a meat-eater or a vegetarian (a non-meat-eater). However, before the demarcation of persons into the dyad, there first has to be a prior stage of categorisation, a ‘metacategorisation’ as it were, of the dyad itself: 

Counterintuitively, categories take relational forms. ... A category consists of a set of actors who share a boundary distinguishing all of them from and relating all of them to at leads one set of actors visibly excluded by that boundary. A category simultaneously lumps together actors deemed similar, splits sets of actors considered dissimilar, and defines relations between the two sets. For obvious examples, consider the following:

Women, a category excluding men

Blacks, a category excluding whites

Slaves, a category excluding masters and other free persons [[12]p. 62]

Social history throws up and creates such categorical dyads frequently, only for such particular dyads to lose their social salience later. Categorical pairings which previously had no meaning or salience in understanding or dividing persons come to have great importance and effect on interpersonal relations and behaviours. Political and social debates and disagreements have, throughout the ages, been thought of in terms of social dyadic categories that were, at the time, matters of great importance, but which now are simply historical artefacts: we no longer categorise people on whether someone is pro-slave or an abolitionist, or a Whig or a Tory; however, other categories have emerged that have similar function within contemporary discussions: whether someone is pro-Invasion or anti-Invasion (of Iraq), for instance, or pro-life/pro-choice. 

	Many specific dyads come to shape social behaviours within a particular historical epoch, but are ultimately impermanent and transitory in their significance. Some others, however, tend to be more obdurate in their occurrence and re-occurrence. This is because they involve using physical differences, generally arising from biological differences, as the basis of dyadic categorisation. Such types of dyads re-occur because of their reliance on readily-available and noticeable biological markers. Unlike a categorisation based upon a Minimal Group Paradigm situation, a biological-marker-based dyad will always tend to divide a given set of individuals the same way. *The effect of systematically different social influence, therefore, will thus always be strongly correlated with a set of systematically different physical and biological differences. “*Even when they employ ostensibly biological markers, such categories always depend on extensive social organization, belief, and enforcement.” [[12], p. 7]

Stereotypes: A partial aside	

Once the metacategorisation process has been completed, and the category of dyadic relation perceived has been imposed upon the social phenomena, the process of intra-dyadic categorisation begins. The dyads both comprise of, and aid the process of, stereotyping. “In a rather formal way, the problem of stereotypes is that of the relation between a set of attributes which vary on continuous dimensions and classifications which are discontinuous.” [[11] p. 132] 

	With respect to the above discussion, it may be illustrative to consider the visual schema drawn in chapter two [reference] to illustrate the concept of the Code. Within the schema, ‘input’ phenomena is processed through a number of discrete stages. The first of these is ‘categorisation’: the conversion of fuzzy and continuous phenomena into a set of discrete ontologies. 

Tilly’s suggestion that social categories are fundamentally dyadic and relational in nature hints towards a sub-process within the process of categorisation: *in order to draw a division within a continuous axis, the continuous axis must first be drawn*. The formation of a continuous scale often seems to form a prerequisite to the creation of discrete ontologies. The assumption that multiple continuous dimensions can be collapsed onto a single continuous dimension itself seems to be a prerequisite condition of this prerequisite condition.  

As was suggested within chapter two [reference], there seems no reason to assume that the underlying logic of categorisation differs fundamentally with respect to whether the processes are explicit (as in ‘codes’) or tacit (as in ‘conventions’). Indeed, it seems reasonable to assume that there is a substantial correspondence between formal and informal categories, with both tacit and explicit ontologies influencing one another. This appears to relate to Tilly’s idea that some categorical boundaries are ‘costlier’ to maintain than others [reference]. It is easier for an institution to maintain a formal categorical distinction between persons if that categorical distinction, and the dyad which underlies it, is commonly and implicitly used amongst much of the populace. Given that the processes of modernity (to keep with the circumscribed definition the author employed within chapter two) involve a substantial increase in the degree of formalisation of knowledge, it is logical to assume that the initial direction of causal categorical influence was from informal to formal – i.e. that administrative organisations initially formalised the categorical distinctions that had hitherto been employed informally. However, both formal and informal categorical systems have co-existed for long enough that one can now assume the influence to go in both directions.

[Internal/external boundaries: onion skin categorisations]

[Also mention Tilly’s article: Social Boundary Mechanisms; and book, Identities, Boundaries and Ties]

The List

With the above discussions, digressions and clarifications in mind, a list that Tilly provides within the book *Durable Inequality,* as a one-page summary of the thesis, may now be more comprehensible:

  - Paired and unequal categories, consisting of asymmetrical relations across a socially recognized (and usually incomplete) dividing line between interpersonal networks, recur in an wider variety of situations, with the usual effect being the unequal exclusion of each network from resources controlled by the other.

  - Two mechanisms we may label *exploitation* and *opportunity hoarding* cause durable inequality when their agents incorporate paired and unequal categories at crucial organizational boundaries.

  - Two further mechanisms we may title *emulation* and *adaptation* reinforce the effectiveness of categorical distinctions.

  - Local categorical distinctions gain strength and operate at lower cost when matched with widely available paired and unequal categories.

  - When many organizations adopt the same categorical distinctions, those distinctions become more pervasive and decisive social life at large.

  - Experience within categorically differentiated settings gives participants systematically different and unequal preparation for performance in new organizations

  - Much of what observers ordinarily interpret as individual differences that create inequality is actually the consequence of categorical organization

  - For these reasons, inequalities by race, gender, ethnicity, class, age, citizenship, educational level, and other apparently contradictory principles of differentiation form through similar social processes and are to an important degree organizationally interchangeable [[12]pp. 8-9]

Though all four of the principles Tilly uses to explain durable inequality are important, the distinction is made between the two principles listed in point 2, and the two principles mentioned in point 3. More explicitly:

  - **Exploitation** and **Opportunity Hoarding** are mechanisms that *cause* durable inequality

  - **Emulation** and **Adaptation** are mechanisms that *develop* and *sustain* durable inequality (respectively)

The author will offer brief summaries of the first two mechanisms, as these help to explain a plausible genesis of such forms of categorical inequality arising from the economic principle of householding. 

Tilly offers the following descriptions of the terms [not quite...] :

  - *Exploitation*[:] operates when powerful, connected people command resources from which they draw significantly increased returns by coordinating the effort of outsiders whom they exclude from the full value added by that effort.

  - *Opportunity hoarding*[:] operates when members of a categorically bounded network acquire access to a resource that is valuable, renewable, subject to monopoly, supportive of network activities, and enhanced by the network’s modus operandi. [[12]p. 10]

Tilly offers the following three examples of opportunity hoarding in practice:

  - [T]he founder of a small manufacturing firm, following models already established in the trade, divides the firm’s work into clusters of jobs viewed as distinct in character and qualifications and then recruits works for those jobs within well-marked categories. As turnover occurs and the firm expands, established workers pass word of available jobs among friends and relatives, collaborating with and supporting then once they join the work force. Those new workers therefore prove more reliable and effective than others hired off the street, and all concerned come to associate job with category, so much so that owner and workers come to believe in the superior fitness of that category’s membership for the particular line of work. [[12]p. 13]

  - Householders in an urban neighbourhood build up a precarious system of trust on the basis of common backgrounds and shared relations to third parties, live with persons and property at risk to that system of trust, and then react violently when newcomers whom they cannot easily integrate into the same networks threaten to occupy part of the territory. In the process, members of the two groups elaborate compelling stories about each other’s perfidy and utter incompatibility. [[12]p. 13]

  - Members of an immigrant stream ... peddle craft goods from their home region on big-city streets, and some of them set up businesses as suppliers, manufacturers, or retail merchants. New immigrants find work in the expanding trade, and not only an immigrant niche but an ethnically specific international connection provides exclusive opportunities for the next generation. [[12]p. 13]

Tilly states that, “In all these cases, organizational improvisations lead to durable categorical inequality.” [[12]p. 13]

	 

It can be pedagogically helpful (and often correct) to think of Opportunity Hoarding as an antecedent and pre-cursor to Exploitation. To use the classical Marxist example, all one needs to do in order to link the former to the latter is to assume the following instance:

  
    
      ****
      **
    
    
      ****
      **
    
  

| Categorically Bounded Network | Capitalists |
| --- | --- |
| Monopolised Resource | Means of Production |

However, not all instances of Opportunity Hoarding lead to Exploitation, and not all instances of Exploitation can easily be shown to have arisen from particular instances of Opportunity Hoarding. 

Summary

This section of the chapter began having introduced Polanyi’s idea that *Householding* represents a very important economic principle; it then proceeded to discuss a number of ideas and theories from the social psychology of groups, before concluding with a brief summary of Charles Tilly’s concept of ‘durable inequality’. The aim of this excursion has been to attempt to corroborate Polanyi’s claim: the *Householding* principle is vital to understanding social and economic relationships, both because it seems to emerge from some relatively universal and ahistorical patterns of social behaviour, and because systematic differences in the ways persons are treated by other persons, and with this differences in opportunities afforded them, has been given as a plausible explanation for many of stark social inequalities which are observed in contemporary society. 

	Furthermore, the salience of certain characteristics resulting from biological differences, such as skin colour and gender, together with the apparent universality of the psychological propensity for dyadic categorisation – as revealed by the Minimal Group Paradigm and related research – suggest that biological and social-discriminatory factors relating to, most obviously, gender and ‘racial’ difference will be heavily correlated *as a rule rather than as an exception*. 

	[Causal diagram?]

The Sick Role

Previous sections of this chapter have, respectively:

  - Introduced Polanyi’s concept of Substantivist Economics

  - Discussed the primacy of the principle of reciprocation to effective social (and by extension economic) relationships, in order to provide a broader justification for Polanyi’s first two economic systems: *reciprocity* and *redistribution*

  - Summarised some concepts and theories from within the field of social psychology in order to provide a broader justification for Polanyi’s third economic system: *householding*

  - Linked the concept of *householding* to Charles Tilly’s concept of Durable Inequality. 

This section will use a number of ideas from each of the prior sections – the sociology of reciprocation, the value of community figuration as a risk-sharing (and from the individual perspective risk-minimising) system, and the apparent ubiquity of social categorical thinking – in order to guide a discussion on sickness and  welfare provision in a broad sense.

[Further explanation/’saying what you’re going to say’]

The Community as Risk Managers

Within chapter one, the author made the claim that the minimising the risk of experiencing absolute hardship is often much more important to people than maximising expected value. Fundamentally, this is what all forms of welfare and social security are about. 

As a relatively simple example of the effectiveness of [without central coordination] as a risk minimising strategy, the author has constructed a very rudimentary agent based model. The model is set up as follows:

  - A contiguous line of 150 agents is created. Each agent thus as two direct neighbours.

  - Each of the 150 agents is initially allotted a finite number of resources, drawn from a Poisson distribution with lambda = 2. More prosaically, each agent could have any (natural) number of resources, including none, but on average the number of resources each agent has is 2

  - After the resources have been allotted, each agent compares the number of resources it has to the number of resources each of its nearest neighbours have.

  - If the agent has less resources than both of its neighbours, then the neighbour with the most resources gives the agent one unit of resource.

  - If the agent has less resources than either of its neighbours, and both neighbours have the same number of resources, then one neighbour is selected to give up a resource with equal probability.

The following graph shows the  effect of the agents following this simple nearest-neighbour decision rule on the distribution of resources amongst a single draw of 150 agents:

  

	

More importantly, from the perspective of welfare, the two parallel horizontal lines below show the number of agents with no resources both before (top line) and after (bottom line) the redistribution procedure:

	

The number of red squares, indicating an agent with no resources, reduces from over 20, to just one. A further iteration of the sharing procedure would reduce the number of resourceless agents to zero. 

	The nearest-neighbour procedure, though effective in many circumstances, is not as successful when most of the resourceless agents are spatially concentrated, as the following suggests:

In the above, 100 of the 150 agents have resources drawn from a Poisson distribution of lambda = 3. Fifty *contiguous* agents, however, are allotted no resources. Both this arrangement, and the previous one, have the same statistical expectation, however in this case the effect of nearest-neighbour redistribution on ameliorating hardship is much reduced. This is also shown in the before-and-after histogram:

Within the model, a communal hardship – affecting the entire population rather than just a proportion of it – is represented by a reduced lambda value. The following show typical patterns of individual hardship when lambda = 1.5, 1.0, and 0.5. 

Lambda = 1.5

Lambda= 1.0

Lambda=0.5

The effect of even simple redistribution, then, means that individuals are less likely to experience life-threatening hardship. When threats occur, they strike at the level of the community, not the individual. 

[The Deserving/Undeserving Criteria]

		[Dyadic thinking]

		[In-group/out-group]

	[The Young and the Old]

		[The creation of childhood]

		[The creation of the old]

			[‘Natural deaths’ as relatively unnatural?]

	[The Sick]

		[Tribal eugenics]

			[Social Darwinism]

		[Extended bad luck]

		[Poorer health]

		[Communal Provisions]

[Workers Mutuals and Co-operatives]

	[Urbanisation]

		[Flight from Rural to Urban centres]

		[Industrial Capitalism]

		[The Creation of Workers]

		[Unions, Mutuals, Co-operatives]

	[In-group categorisation by similarity of circumstance, rather than familial ties or origin]

		[Pseudo-kin]

	[Onion-skin categorisation]

		[Tilly’s Internal/External Categories]

		[Marx’s obsession with attacking other left-wing radicals]

		[Psychological Evidence]

			[Change Blindness example]

	[Various de Swaan and Harris references]

 

Categorical Thinking in Modern Welfare Provision

[Introductory Paragraph]

[Deserving/Undeserving]

	[Charles Booth’s Poverty Map in London]

[Employed/unemployed]

[ILO Categorisations]

Historical Social Categories

John Welshman has provided a useful historical perspective on current Welfare to Work debates, in particular with respect to the shifting definitions of ‘unemployable’ groups, and shifting attitudes and targets with respect to different groups of people:

Worklessness has ... been defined as detachment from the formal labour market, in particular areas, and among particular groups. Thus workless individuals include those who are unemployed and claiming unemployment benefits, individuals who are economically inactive and eligible for inactive benefits, and individuals who are working exclusively in the informal economy. (The last two groups may or may not be claiming benefits.)  Thus worklessness broadens traditional definitions of unemployment, by covering those who are unemployed or economically inactive and in receipt of benefits.

The fluidity of the concept of unemployment, and the fact that employment has been defined as much by social and political factors as by economic ones, has long been recognized. Groups deemed unemployable in one period have subsequently been incorporated into the labour market in another.

As Welshman states elsewhere, with respect to Beveridge, the term ‘unemployable’ has “no real meaning – the best carpenter in the world [is] unemployable as a printer”, and the place an individual or group has within the formal economy has a great deal to do with the structure of the economy and the particular skills and knowledge it most and least demands. As Charlesworth *et al* state with respect to de-industrialisation in the UK:

Many of the changes that have taken place to the economic order have increased working class people’s exposure to situations in which they find themselves evaluated, judged and graded against formalized criteria. [A]s employers no longer needed young working class people in such numbers after 1979, the route into employment changed radically. Until sometime in the 1970s, a majority of school leavers went into employment in *relatively *well paid jobs with no qualifications. That has now virtually ceased and entrance to work is now mediated by a host of post-sixteen training and educational programmes so that even many manual workers go through some ‘post-compulsory’ education.

This is a crucial change in the experience of entrance to the labour market and in young people’s chances of earning enough to support stable patterns of relationships. What we now have are conditions in which many more experience education, but the outcome is less certain and the experience is fraught with ambiguity. Many feel press-ganged into tertiary colleges as a condition of receiving state benefit, and have the experience of being forced to compete in conditions in which they are judged, informally as well as formally, for credentials they feel are worthless.

De-industrialisation thus, to a large extent, *creates* the unemployable, because the skills and experiences which were hitherto considered valuable as economic commodities rapidly lose their value. 

	Social aetiology, outside of the social sciences, is seldom practiced however, and thus public and political debates have tended to assume the reasons behind the non-employment of members of groups for which there exists the normative expectation of formal work – socially non-exempt groups like lone parents and the long term sick, rather than socially exempt groups like pensioners and students – are to do with individual or cultural *pathology*, rather than broader social structural forces. 

In the Nineteenth century, for example, popular writing on unemployability tended to be closely connected to what Welshman refers to as ‘the residuum’: a rather less euphemistic pre-curser to more contemporary debate about the ‘social underclass’.  Public and political debate has tended to focus on attempting to determine between the ‘deserving’ and ‘undeserving’ nonemployed. Famously, Charles Booth’s lowest employment class, class ‘A’, included what were described as “labourers, loafers, semi-criminals, some street sellers and street performers, the homeless, and people who were both working and engaged in crime.” Even though there were no sharp empirical dividing lines between Booth’s lowest, ‘undeserving’ class ‘A’, and the next lowest, ‘deserving’ class, ‘B’, Booth was still careful to *attempt* to make the distinction. As Welshman states, similar distinctions of sentiment - into ‘undeserving’ and ‘deserving’ nonemployed – were also made by Rowntree and even Beveridge. Although there were differences between the extent to which individuals’ nonemployment was attributed to endogenous or exogenous factors, the propensity to create a normative distinction between ‘deserving’ and ‘undeserving’ appears strong and deep-rooted.

Modern Debates and Social Categories

Modern political debate and description of the ‘problem’ nonemployed – lone parents and incapacity benefit claimants – tends to be careful not to fall into the late Nineteenth and early Twentieth century pattern of pathologising the *individual*, but instead casually presents explanations for such working age benefit claimants in terms of a pathological, ‘sick’, *culture *of welfare dependency and labour market detachment. Interestingly, *New Labour* documents often suggest that Social Security provisions are part of the problem:

IB trends over the past 20-30 years reflect a fundamental shift in the *culture* that  surrounds sickness, disability and incapacity for work.

[A]lthough never official policy, rising IVB was condoned as a means of reducing headline unemployment rates, and becomes a route to early retirement

Perhaps, in the idealistic mood of the times, [Beveridge] assumed that only those who were truly sick and incapacitated would claim benefit

In the summer we will set out in detail in a Green Paper how we will radically change the benefit system so it reflects all that we have learnt about the needs of those on IB. Together – working with employers, GPs, special interest groups and claimants themselves – we can replace *the sicknote culture *with one of hope and opportunity.

Incapacity Benefit is out of date – our radical plans will sweep aside a system that branded people incapable and help claimants focus on what they can do, not what they can’t.

The vast majority of people – around 80 to 90 per cent – making a claim for incapacity benefits want and expect to get back into work. It is the system that has failed them, by not providing the help and support they need. There are several shortcomings in the system as it currently stands.

  - Little is done to prevent people moving onto incapacity benefits.

  - The gateway to the benefits is poorly managed – with claimants receiving incapacity benefits before passing the main medical test.

  - The benefits trap people into a lifetime of dependency – the longer a person remains on benefits, the less chance they have of leaving.

  - There are perverse benefit incentives – paying more the longer people claim.

  - Almost nothing is expected of claimants and little support is offered. Those who try to plan their return to work through volunteering and training perceive that they run  the risk of proving themselves capable of work and therefore losing their entitlement.

  - The very name of the benefit sends a signal that a person is incapable and that there is nothing more that can be done.

Chapter References

Notes

Polanyi: types of economy

		Exploitation of reciprocal behaviour as one of Cialdini’s 6 ‘universal principles’ 

	Redistributive

	Household

		Larger size of population; bifurcates into differential social groups; then preference to reciprocate more with 

	Market

		External Market

			Trade between urban centres

		Internal Market

			Monetarised trade between individual and local agents

				Had to be ‘created’ by state intervention

					Speenhamland: informal agreement – emulated strategy amongst elites

‘Marked’ness – method of investigating social schemas (‘black president’ cf ‘white president’; ‘female president’ cf ‘male president’) – Social groupings – inherent complexity and ‘clusteredness’ of stereotypes.

Tilly’s Durable Inequality Notes

Systems thinking: “the fading of systems theories a generation ago” [p. 21]

*Systems theories * impute self-maintaining logics to social structures, from groups, organizations, or institutions to that big, vague structure that analysts refer to as “society,” [p. 18]

The unjustly neglected institutional economist John R. Commons (1934) insisted sixty years ago that economics should begin its analyses with transactions, not individuals. [p. 18]

[Refers to Commons, John R., 1934, *Institutional Economics: Its Place in Political Economy*, New York: Macmillan.]

Work Based Social Categories

Unemployment, as the term is used and reported in surveys today, is a relatively new concept. The term was invented in Britain, and first “came into use in 1886 when the Board of Trade asked the trade unions to provide monthly statistics of the number of the members who were not in employment”. 

Since 1984, the British Labour Force Survey, in order to allow more direct comparison with other nations, has used the International Labour Organisation’s definition of unemployment. This has involved categorising everyone in a small number of categories

(Figure 13)

Figure 13. International Labour Organisation Classifications

Source: ONS 2006, 'How exactly is unemployment measured?'

Economic Activity and Economic Inactivity

With regard to the above figure, many people I have spoken to are surprised that one is classed as ‘economically active’ if one is claiming Job Seekers Allowance, but ‘economically inactive’ if one is performing a wide range of social duties which, if not performed by that individual, would still need to be performed, and would have a tangible financial cost if they were to be performed by someone ‘in employment’. 

Examples of Economically Inactive Activities

Prime examples of these kinds of economically valuable, ‘economically inactive’ activities are innumerable, and include: grandparents who look after grandchildren while the parents are in employment; parents – both male and female – who clean and provide food for the rest of their household; people providing ‘free’ labour in the form of house improvements like roofing and decorating; people who organise social events and ‘hook up’ single friends with potential mates; persons with a career in accountancy who provide friends and family with financial planning advice; full-time carers who look after convalescent and terminally ill kin; friends who inform people looking to start a musical group or other enterprise of potential contacts with similar interests; persons who volunteer to help out at local community centres or Citizens Advice Bureaus; people who have allotments and distribute fruit, vegetables and preserves to their relatives; people who provide a place to stay to a friend who needs to move because of an acrimonious divorce; people who provide advice and emotional support to friends at times of personal distress; people who provide romantic and sexual ‘services’ for other people; people who drive who agree to meet other people at an airport or train station at a given time; people who comfort distressed children; retired teachers who provide tutoring for nieces and nephews three months from their GCSE exams; people who provide an immersive, interactive package of evening entertainment for other people; people who create and contribute to free, open-source software such as *Mozilla Firefox* and *Open Office*...

In what sense, then, are these people *not* economically active? What are the reasons for this distinction? The answer seems to be not to do with the goods and services the economically inactive produce and perform for one another, but with the service the unemployed provide to employers who don’t employ them: in not being employed, in being ‘surplus labour’ in want and need of jobs, the unemployed are ‘economically active’ in the sense that they make it harder for the employed to demand higher wages. They are economically active, not as people, but as inhibitory forces against wage inflation.

Chapter Endnotes

1.	Tilly, C., *Reflections on the History of European State-making*, in *The Formation of National States in Western Europe*, C. Tilly, Editor. 1975, Princeton University Press: Princeton. p. 3-83.

2.	Polanyi, K., *The Great Transformation: The Political and Economic Origins of Our Time*. 2001 [1957], Boston: Beacon Press.

3.	Pearsall, J., et al., eds. *The Concise Oxford English Dictionary*. Tenth ed. 1999, Oxford University Press: Oxford.

4.	Smith, A., *An Inquiry into the Nature and Causes of the Wealth of Nations*. 1776, www.bibliomania.com.

5.	Polanyi, K., *Livelihood of Man*. Studies in Social Discontinuity. 1978, Burlington: Academic Press.

6.	Cialdini, R.B., *Influence: The psychology of persuasion*. 2007, London: HarperPress.

7.	Swift, J., *Gulliver's Travels*. Second Edition ed. 1970 [1727], London: W.W. Norton & Company.

8.	Harris, J.R., *The Nurture Assumption: Why children turn out the way they do*. Paperback ed. 1999, London: Bloomsbury.

9.	Nisbett, R. and L. Ross, *Human Inference: Strategies and Shorcomings of Social Judgment*. The Century Psychology Series, ed. J.J. Jenkins, W. Mischel, and W.W. Hartup. 1980, Englewood Cliffs: Prentice-Hall.

10.	Tilly, C., *Why?* 2006, Oxford: Princeton University Press.

11.	Tajfel, H., *Human Groups & Social Categories*. Studies in Social Psychology. 1981, Cambridge: Cambridge University Press.

12.	Tilly, C., *Durable Inequality*. 1999, California: University of California Press. 310.

13.	Welshman, J., *The concept of the unemployable.* Economic History Review, 2006. 59(3): p. 578-606.

14.	Charlesworth, S.J., P. Gilfillan, and R. Wilkinson, *Living inferiority.* Br Med Bull, 2004. 69(1): p. 49-60.

15.	Lister, R., ed. *Charles Murray and the Underclass: The Developing Debate*. 3 ed. Choice in Welfare, ed. I.H.a.W. Unit. 1999 [1996], Civitas: London. 190.

16.	Aylward, M. and G. Waddell, *The Scientific and Conceptual Basis of Incapacity Benefit*. 2005, London: The Stationary Office.

17.	Pensions, D.f.W.a., *Johnson announces summer green paper to reform Incapacity Benefit as radical "pathways" pilots get 10,000 off IB in a year*. 2005.

18.	DWP, *A New Deal for Welfare: Empowering people to work*, D.o.W.a. Pensions, Editor. 2006, The Stationery Office.

19.	Thomas, R., *Is the ILO definition of unemployment a capitalist conspiracy?* Radical Statistics, 2005(88): p. 4-21.

20.	Garside, W.R., *The Measurement of Unemployment: Methods and Sources in Great Britain 1850-1979*. 1980, Oxford: Basil Blackwell.
